#!/usr/bin/env bash
#
# demo.sh — THE FOUR DEMONSTRATIONS D6 OWES, PLUS THE ONE IT IMPLIES.
#
# The 2026-07-28 stranger audit's F6: a copy of the tree, `git init`, one commit
# (`ff80b8f`), a clean run; then ONE LINE of `surface1.lisp` changed so that real
# behaviour changed and no declared version integer moved
# (`(defun expansion-policy-max-source-depth () 48)` -> `… () 40)`), and a second
# run.  Both runs labelled `ff80b8f`.  Transcripts BYTE-IDENTICAL.  The evidence was
# wearing a nametag that was not its own.
#
# This script re-stages that exact experiment against the Errata 0.3 apparatus and
# records what happens.  It demonstrates:
#
#   D1  SAME BYTES -> SAME DIGEST         (twice in place, and from a copy at
#                                          another path — content, not location)
#   D2  ONE BEHAVIOURAL BYTE -> DIFFERENT DIGEST
#   D3  SAME GIT HEAD + DIRTY TREE -> DIFFERENT DIGEST   (F6, answered)
#   D4  DIFFERENT HUMAN LABEL -> SAME DIGEST             (the label is not the subject)
#   D5  and the consequence: the two transcripts are NO LONGER byte-identical
#
# Nothing here touches the real tree.  Everything happens in a scratch copy.
set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
S1="$(cd "$HERE/.." && pwd)"; S1="$(cd "$S1/.." && pwd)"   # …/language-surface-1
LL="$(cd "$S1/../.." && pwd)"
OUT="$HERE/DEMONSTRATIONS.txt"
DIGEST="$S1/errata-0.3/subject-digest.sh"

WORK="$(mktemp -d /tmp/surface1-digest-demo.XXXXXXXX)" || exit 2
trap 'rm -rf "$WORK"' EXIT

build() {   # build <dest>
  mkdir -p "$1/canonical-datum/common-lisp" "$1/mneme"
  cp "$LL/canonical-datum/common-lisp/package.lisp" "$1/canonical-datum/common-lisp/"
  cp "$LL/canonical-datum/common-lisp/cd0.lisp"     "$1/canonical-datum/common-lisp/"
  for d in kernel0 language-core-0 language-slice-0 language-slice-1 \
           language-slice-2 language-surface-0; do
    cp -a "$LL/mneme/$d" "$1/mneme/"
  done
  cp -a "$S1" "$1/mneme/language-surface-1"
  rm -rf "$1/mneme/language-surface-1/audits"
  rm -f  "$1/mneme/language-surface-1/errata-0.3/teeth/OUT-"*.txt
  rm -f  "$1/mneme/language-surface-1/RUN-"*.txt
}

exec > >(tee "$OUT") 2>&1

echo "SURFACE /1 ERRATA 0.3 — SUBJECT-DIGEST DEMONSTRATIONS"
echo "generated by errata-0.3/digest-demo/demo.sh; every value below was computed, not quoted"
echo

# ---------------------------------------------------------------------------
echo "=== D1 · SAME BYTES -> SAME DIGEST ==============================="
A1="$(bash "$DIGEST" "$S1")"
A2="$(bash "$DIGEST" "$S1")"
echo "in place, first  : $A1"
echo "in place, second : $A2"
build "$WORK/copy"
COPY="$WORK/copy/mneme/language-surface-1"
A3="$(bash "$COPY/errata-0.3/subject-digest.sh" "$COPY")"
echo "a COPY at another path, its own script:"
echo "                   $A3"
echo "  location        $COPY"
if [ "$A1" = "$A2" ] && [ "$A2" = "$A3" ]; then
  echo "  RESULT: IDENTICAL.  The digest is a function of CONTENT, not of location,"
  echo "  not of time, and not of which checkout it was computed in."
else
  echo "  RESULT: *** MISMATCH — the digest is not content-determined ***"
fi
echo

# ---------------------------------------------------------------------------
echo "=== D2 · ONE BEHAVIOURAL SOURCE BYTE -> DIFFERENT DIGEST ========="
build "$WORK/mut"
MUT="$WORK/mut/mneme/language-surface-1"
B1="$(bash "$MUT/errata-0.3/subject-digest.sh" "$MUT")"
sed -i 's/(defun expansion-policy-max-source-depth () 48)/(defun expansion-policy-max-source-depth () 40)/' \
    "$MUT/surface1.lisp"
B2="$(bash "$MUT/errata-0.3/subject-digest.sh" "$MUT")"
echo "the audit's own mutation: max-source-depth 48 -> 40"
echo "  declared versions touched: NONE (grammar, procedure and policy integers unchanged)"
echo "  bytes changed: 1"
echo "before : $B1"
echo "after  : $B2"
if [ "$B1" != "$B2" ]; then
  echo "  RESULT: DIFFERENT.  A behavioural change that moves no version integer"
  echo "  moves the digest, because the digest measures bytes and not declarations."
else
  echo "  RESULT: *** IDENTICAL — the digest does not see the subject ***"
fi
echo "which member changed, per the rendering:"
diff <(bash "$MUT/errata-0.3/subject-digest.sh" --render "$MUT") \
     <(cd "$WORK/copy/mneme/language-surface-1" && bash errata-0.3/subject-digest.sh --render .) \
  | grep -E '^[<>].*surface1\.lisp' || true
echo

# ---------------------------------------------------------------------------
echo "=== D3 · SAME GIT HEAD + DIRTY TREE -> DIFFERENT DIGEST (F6) ====="
build "$WORK/gitrepo"
G="$WORK/gitrepo"
( cd "$G" && git init -q . && git add -A -f >/dev/null 2>&1 \
  && git -c user.name=teeth -c user.email=teeth@local commit -qm "subject" >/dev/null 2>&1 )
GT="$G/mneme/language-surface-1"
HEAD_BEFORE="$(git -C "$G" rev-parse --short HEAD)"
C1="$(bash "$GT/errata-0.3/subject-digest.sh" "$GT")"
sed -i 's/(defun expansion-policy-max-source-depth () 48)/(defun expansion-policy-max-source-depth () 40)/' \
    "$GT/surface1.lisp"
HEAD_AFTER="$(git -C "$G" rev-parse --short HEAD)"
C2="$(bash "$GT/errata-0.3/subject-digest.sh" "$GT")"
echo "git HEAD, clean tree : $HEAD_BEFORE"
echo "git HEAD, dirty tree : $HEAD_AFTER      <- THE OLD LABEL.  Unchanged."
echo "git status           : $(git -C "$G" status --porcelain | head -3 | tr '\n' ' ')"
echo "digest, clean tree   : $C1"
echo "digest, dirty tree   : $C2"
if [ "$HEAD_BEFORE" = "$HEAD_AFTER" ] && [ "$C1" != "$C2" ]; then
  echo "  RESULT: the commit id says the SAME THING about two different subjects."
  echo "  The digest says two different things.  This is F6, and it is answered."
else
  echo "  RESULT: *** the demonstration did not stage — inspect by hand ***"
fi
echo

# ---------------------------------------------------------------------------
echo "=== D4 · DIFFERENT HUMAN LABEL -> SAME DIGEST ===================="
E1="$(SURFACE1_SUBJECT_LABEL="a-label" bash "$DIGEST" "$S1")"
E2="$(SURFACE1_SUBJECT_LABEL="a-completely-different-label" bash "$DIGEST" "$S1")"
E3="$(SURFACE1_SUBJECT_LABEL="ff80b8f" bash "$DIGEST" "$S1")"
echo "label 'a-label'                      : $E1"
echo "label 'a-completely-different-label'  : $E2"
echo "label 'ff80b8f'                       : $E3"
if [ "$E1" = "$E2" ] && [ "$E2" = "$E3" ]; then
  echo "  RESULT: IDENTICAL.  The label cannot reach the digest — which is the whole"
  echo "  point of keeping the label and marking it ADVISORY rather than deleting it."
else
  echo "  RESULT: *** the label leaked into the measurement ***"
fi
echo

# ---------------------------------------------------------------------------
echo "=== D5 · THE CONSEQUENCE: THE TRANSCRIPTS NO LONGER MATCH ========"
echo "F6's finding was not that the label was wrong in the abstract — it was that TWO"
echo "MATERIALLY DIFFERENT SUBJECTS PRODUCED BYTE-IDENTICAL TRANSCRIPTS.  So: run the"
echo "full evidence runner on both trees of D3 and diff the captures."
CLEANRUN="$WORK/cleanrun"; DIRTYRUN="$WORK/dirtyrun"
build "$CLEANRUN"
build "$DIRTYRUN"
sed -i 's/(defun expansion-policy-max-source-depth () 48)/(defun expansion-policy-max-source-depth () 40)/' \
    "$DIRTYRUN/mneme/language-surface-1/surface1.lisp"
( cd "$CLEANRUN/mneme/language-surface-1" && bash run-surface1-candidate.sh >/dev/null 2>&1 )
echo "clean subject, runner exit $?"
( cd "$DIRTYRUN/mneme/language-surface-1" && bash run-surface1-candidate.sh >/dev/null 2>&1 )
echo "changed subject, runner exit $?  (a changed ceiling is a real regression; the"
echo "  suite is entitled to refuse it — what matters here is the IDENTIFICATION)"
for f in RUN-SELFTEST.txt RUN-STUB-IMAGE.txt RUN-APPLICATION.txt \
         RUN-REPRODUCTION.txt RUN-REPRODUCTION-II.txt RUN-REPRODUCTION-III.txt; do
  a="$CLEANRUN/mneme/language-surface-1/$f"
  b="$DIRTYRUN/mneme/language-surface-1/$f"
  if cmp -s "$a" "$b"; then
    echo "  $f  *** BYTE-IDENTICAL — the F6 defect would still be present ***"
  else
    echo "  $f  differs (first difference at byte $(cmp "$a" "$b" 2>/dev/null | sed 's/.*byte //;s/,.*//'))"
  fi
done
echo
echo "and the digests those two runs printed:"
grep -h '^subject-digest' "$CLEANRUN/mneme/language-surface-1/RUN-EXITCODES.txt" \
                          "$DIRTYRUN/mneme/language-surface-1/RUN-EXITCODES.txt"
echo

# ---------------------------------------------------------------------------
echo "=== D6 · TRANSCRIPT STABILITY FOR AN UNCHANGED SUBJECT ==========="
echo "The mirror obligation: if a changed subject must change the evidence, an"
echo "UNCHANGED subject must not.  Before Errata 0.3 the two reproduction transcripts"
echo "printed an absolute path and the freeze packet's manifest failed on exactly"
echo "those two files.  They no longer print it."
SNAP="$WORK/snap"; mkdir -p "$SNAP/a" "$SNAP/b"
cp "$CLEANRUN/mneme/language-surface-1/RUN-"*.txt "$SNAP/a/"
( cd "$CLEANRUN/mneme/language-surface-1" && bash run-surface1-candidate.sh >/dev/null 2>&1 )
cp "$CLEANRUN/mneme/language-surface-1/RUN-"*.txt "$SNAP/b/"
if diff -r "$SNAP/a" "$SNAP/b" >/dev/null; then
  echo "  re-run in place: ALL SEVEN TRANSCRIPTS BYTE-IDENTICAL"
else
  echo "  re-run in place: *** transcripts changed with no change of subject ***"
  diff -r "$SNAP/a" "$SNAP/b" | head -20
fi
build "$WORK/elsewhere"
( cd "$WORK/elsewhere/mneme/language-surface-1" && bash run-surface1-candidate.sh >/dev/null 2>&1 )
SAME=1
for f in RUN-SELFTEST.txt RUN-STUB-IMAGE.txt RUN-APPLICATION.txt \
         RUN-REPRODUCTION.txt RUN-REPRODUCTION-II.txt RUN-REPRODUCTION-III.txt \
         RUN-EXITCODES.txt; do
  cmp -s "$SNAP/b/$f" "$WORK/elsewhere/mneme/language-surface-1/$f" || { SAME=0; echo "  differs at a second location: $f"; }
done
if [ "$SAME" -eq 1 ]; then
  echo "  run from a SECOND SCRATCH COPY at a different absolute path:"
  echo "  ALL SEVEN BYTE-IDENTICAL."
else
  echo "  run from a SECOND SCRATCH COPY at a different absolute path:"
  echo "  the file(s) named above still carry their location.  Each such line is"
  echo "  an absolute path printed into tracked evidence; the cure is the one"
  echo "  applied to REPRODUCTION.lisp and REPRODUCTION-II.lisp — print a"
  echo "  two-component PLACE, or nothing, and let the digest say WHICH BYTES."
  echo "  The offending line, if it is REPRODUCTION-III.txt, is"
  echo "  errata-0.3/REPRODUCTION-III.lisp:78 — \`(format t \"  directory   ~A~%\" (truename …))\`."
fi
echo "  HONEST LIMIT on the ones that are stable: the reproductions still print a"
echo "  two-component PLACE ('.../mneme/language-surface-1/').  A copy that renamed"
echo "  those two directories would differ there, and rightly — that is a"
echo "  description of the layout, not of the machine."
echo
echo "WHAT NONE OF THIS ESTABLISHES: that the measured bytes are the RIGHT bytes."
echo "A digest is an ACCOUNT of what was loaded, never an AUTHENTICATION of it."
