#!/usr/bin/env bash
#
# check-form1-transcript.sh — the reconciler for Language Form /1, Candidate /0.
#
# THIS IS NOT A GOVERNING FLOOR.  It is the second half of a local runner pair:
# run-form1-candidate.sh produces the raw captures, this script reconciles them
# and writes RUN-TRANSCRIPT-CHECK.txt.  It is added to no verify-*.sh.
#
# WHY IT EXISTS: this tree already contains a RUN-TRANSCRIPT-CHECK.txt whose
# generator does not exist anywhere in the repository.  A reconciliation nobody
# can re-run is a claim, not a check.  This is the generator that should have
# existed, and every number it prints is derived from the capture on disk.
#
# It never re-runs the suites.  It never trusts a footer.  It never trusts a
# banner.  It reads bytes.
#
# Reproducibility: the artifact is a pure function of the two captures and the
# retained exit codes.  No timestamp, no hostname, no pid, no absolute path and
# no $RANDOM reaches the output; LC_ALL=C fixes collation.  Two runs over the
# same captures produce byte-identical files.
#
# Run: bash check-form1-transcript.sh    (from any cwd; after the runner)

set -uo pipefail
export LC_ALL=C

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$HERE/RUN-TRANSCRIPT-CHECK.txt"
EXITCODES="$HERE/RUN-EXITCODES.txt"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# ── The ONLY hard-coded things in this script, all of them declared in the
#    artifact header.  None of them is a count, a total, or an expected N.
#
#  (1) which captures to read — the two files the runner writes
CAPTURES=("RUN-SELFTEST.txt" "RUN-APPLICATION.txt")
LABELS=("form1-selftest" "de-forma-petente/APPLICATION")
EXITKEYS=("form1-selftest" "de-forma-petente")
#
#  (2) the verdict-line shapes, taken from the suites' OWN printers in this
#      layer family — both are live in the tree and they differ:
#        form0-selftest.lisp      (format t "  ok   ~A~%")        unnumbered
#        form0-selftest.lisp      (format t "  FAIL ~A~%")        unnumbered
#        de-forma-dormiente/…     (format t "  [~2,'0D] ok   ~A~%")   numbered
#        de-pignore/APPLICATION   (format t "  [~2D] …ok  /FAIL…~%")  numbered
#      so the reconciler must accept BOTH and must not assume which Form /1
#      chose.  Which one it actually found is reported, never presumed.
VERDICT_RE='^[[:space:]]{0,6}(\[[[:space:]]*[0-9]+\][[:space:]]*)?(ok|FAIL)([[:space:]]|$)'
OK_RE='^[[:space:]]{0,6}(\[[[:space:]]*[0-9]+\][[:space:]]*)?ok([[:space:]]|$)'
FAIL_RE='^[[:space:]]{0,6}(\[[[:space:]]*[0-9]+\][[:space:]]*)?FAIL([[:space:]]|$)'
INDEXED_RE='^[[:space:]]{0,6}\[[[:space:]]*[0-9]+\]'
#
#  (3) the footer shape — a tally line, whichever word the suite uses.  The
#      word decides the ARITHMETIC and is read off the line, not assumed:
#        "N passed / M failed"          => total = N + M   (form0, core0, …)
#        "N checks passed / M failed"   => total = N + M   (de-forma-dormiente)
#        "N checks produced / M failed" => total = N       (de-pignore)
FOOTER_RE='[0-9]+[[:space:]]+(checks[[:space:]]+)?(passed|produced)[[:space:]]*/[[:space:]]*[0-9]+[[:space:]]+failed'
#
#  (4) the SBCL implementation-failure markers.  A typed protocol refusal that
#      the suite RETAINS and prints is the protocol working; an unhandled
#      condition is the implementation dying.  Only the second set is here.
#      Deliberately absent: "caught STYLE-WARNING" and "caught N STYLE-WARNING
#      condition", which appear in healthy runs of this tree.
IMPL_RE='Unhandled [A-Za-z0-9:_.-]+ in thread|Backtrace for:|debugger invoked on a|^;[[:space:]]*caught ERROR:|caught [0-9]+ ERROR condition|Evaluation aborted on'

PROBLEMS=()
note_problem() { PROBLEMS+=("$1"); }

: >"$OUT"
emit()  { printf '%s\n' "$*" >>"$OUT"; }
field() { printf '  %-25s %s\n' "$1" "$2" >>"$OUT"; }
cont()  { printf '  %-25s %s\n' "" "$1" >>"$OUT"; }

# ── Header — and it is TRUE of this script ───────────────────────────────────
emit "RUN-TRANSCRIPT-CHECK — Language Form /1, Candidate /0"
emit "generated by check-form1-transcript.sh from the RAW captures beside it"
emit ""
emit "METHOD (this header describes the script that wrote this file):"
emit "  Every count below is derived by scanning the named capture. Nothing is"
emit "  copied from a footer, a banner, or a previous artifact. The suites were"
emit "  not re-run; only bytes already on disk were read."
emit "  Verdict lines are recognised by the two printer shapes live in this"
emit "  layer family — unnumbered  '  ok   <label>' / '  FAIL <label>'  and"
emit "  numbered  '  [NN] ok   <label>' / '  [NN] FAIL <label>'. Which shape a"
emit "  suite used is reported, not assumed."
emit "  The footer is the LAST non-verdict line matching '<N> [checks]"
emit "  passed|produced / <M> failed'. The word decides the arithmetic:"
emit "  'passed' => total = N + M;  'produced' => total = N. Verdict lines are"
emit "  excluded from the footer search so a label quoting a tally cannot be"
emit "  mistaken for the tally."
emit "  HARD-CODED, exhaustively: (1) the two capture filenames; (2) the verdict"
emit "  token set {ok, FAIL} and the two printer shapes above; (3) the footer"
emit "  word set {passed, produced}; (4) the SBCL implementation-failure marker"
emit "  patterns. NO expected check count, NO expected total, NO expected exit"
emit "  code and NO expected failure count appears anywhere in the script."
emit "  KNOWN LIMIT, stated because it is real: for a suite using the UNNUMBERED"
emit "  printer a renamed verdict token cannot be detected structurally — it"
emit "  surfaces instead as 'footer == rendered' FAILING, which is checked. For"
emit "  the numbered printer the token is read off each line and checked exactly."
emit "  Exit codes are read from RUN-EXITCODES.txt, written by the runner; if"
emit "  that file is absent the exit checks report UNKNOWN, never PASS."

# ── analyse one capture ──────────────────────────────────────────────────────
analyse() {  # $1=label  $2=capture-basename  $3=exit-key
  local label="$1" base="$2" key="$3"
  local cap="$HERE/$base"

  emit ""
  emit "-- $label   ($base)"

  if [ ! -f "$cap" ]; then
    field "capture" "MISSING — $base is not on disk"
    cont  "run  bash run-form1-candidate.sh  first"
    note_problem "$label: capture missing"
    return
  fi

  local bytes lines
  bytes="$(wc -c <"$cap" | tr -d ' ')"
  lines="$(wc -l <"$cap" | tr -d ' ')"
  field "capture method" "direct sbcl --non-interactive --load, stdout+stderr,"
  cont  "UNFILTERED (no grep or sed in the capture path)"
  field "capture size" "$bytes bytes, $lines lines"

  # ── exit code (retained, not re-derived) ───────────────────────────────────
  local rc="UNKNOWN"
  if [ -f "$EXITCODES" ]; then
    rc="$(awk -v k="$key" '$1==k {print $2; found=1} END{if(!found) print "UNKNOWN"}' "$EXITCODES" | head -1)"
  fi
  field "process exit code" "$rc"

  # ── the body ───────────────────────────────────────────────────────────────
  local n_ok n_fail n_rendered
  n_ok="$(grep -cE "$OK_RE" "$cap" || true)"
  n_fail="$(grep -cE "$FAIL_RE" "$cap" || true)"
  n_rendered=$(( n_ok + n_fail ))

  # ── the footer ─────────────────────────────────────────────────────────────
  local footline core fn fword ff ftotal
  footline="$(grep -vE "$VERDICT_RE" "$cap" | grep -E "$FOOTER_RE" | tail -1 || true)"

  if [ -z "${footline:-}" ]; then
    field "footer line" "ABSENT — no tally line in this capture"
    field "rendered verdict lines" "$n_rendered  ($n_ok ok, $n_fail FAIL)"
    field "footer == rendered" "UNKNOWN — nothing to compare against"
    note_problem "$label: no footer tally line"
    fn=""; ff=""; ftotal=""
  else
    core="$(printf '%s\n' "$footline" | grep -oE "$FOOTER_RE" | tail -1)"
    fn="$(printf '%s\n' "$core" | grep -oE '^[0-9]+')"
    fword="$(printf '%s\n' "$core" | grep -oE '(passed|produced)' | head -1)"
    ff="$(printf '%s\n' "$core" | grep -oE '[0-9]+[[:space:]]+failed$' | grep -oE '^[0-9]+')"
    if [ "$fword" = "produced" ]; then
      ftotal="$fn"
    else
      ftotal=$(( fn + ff ))
    fi
    field "footer line" "$footline"
    field "footer semantics" "'$fword' => total = $ftotal, failed = $ff"
    field "footer total" "$ftotal"
    field "rendered verdict lines" "$n_rendered  ($n_ok ok, $n_fail FAIL)"
    if [ "$ftotal" -eq "$n_rendered" ]; then
      field "footer == rendered" "PASS"
    else
      field "footer == rendered" "FAIL — footer says $ftotal, body renders $n_rendered"
      note_problem "$label: footer $ftotal != rendered $n_rendered"
    fi
  fi

  # ── numbering ──────────────────────────────────────────────────────────────
  local idx="$WORK/idx.$key"
  grep -oE "$INDEXED_RE" "$cap" 2>/dev/null | grep -oE '[0-9]+' | sed -E 's/^0+([0-9])/\1/' >"$idx" || true
  local n_idx
  n_idx="$(wc -l <"$idx" | tr -d ' ')"

  if [ "$n_idx" -eq 0 ]; then
    field "numbering" "ABSENT — this suite uses the UNNUMBERED printer"
    cont  "(contiguity is not applicable; token drift would"
    cont  " surface as 'footer == rendered' failing, above)"
  else
    local summary count max missing dups
    summary="$(awk '
      { v=$1+0; n++; if (seen[v]++) dup[v]=1; if (v>max) max=v }
      END {
        missing=""
        for (i=1;i<=max;i++) if (!(i in seen)) missing = missing (missing==""?"":",") i
        dn=0; for (v in dup) dl[++dn]=v+0
        for (i=1;i<=dn;i++) for (j=i+1;j<=dn;j++) if (dl[j]<dl[i]) { t=dl[i]; dl[i]=dl[j]; dl[j]=t }
        dups=""; for (i=1;i<=dn;i++) dups = dups (dups==""?"":",") dl[i]
        printf "%d %d %s %s\n", n, max, (missing==""?"-":missing), (dups==""?"-":dups)
      }' "$idx")"
    count="$(printf '%s' "$summary" | cut -d' ' -f1)"
    max="$(printf '%s' "$summary" | cut -d' ' -f2)"
    missing="$(printf '%s' "$summary" | cut -d' ' -f3)"
    dups="$(printf '%s' "$summary" | cut -d' ' -f4)"

    if [ "$missing" = "-" ] && [ "$dups" = "-" ] && [ "$count" -eq "$max" ]; then
      field "numbers contiguous 1..N" "PASS  (1..$max, $count indices)"
    else
      field "numbers contiguous 1..N" "FAIL  (max $max, $count indices seen)"
      [ "$missing" != "-" ] && cont "gaps — indices absent: $missing"
      [ "$dups" != "-" ]    && cont "duplicated indices: $dups"
      note_problem "$label: numbering not contiguous 1..$max"
    fi

    if [ "$n_idx" -ne "$n_rendered" ]; then
      field "indexed == verdicts" "FAIL — $n_idx indexed lines, $n_rendered verdict lines"
      cont  "(a mixed or drifting printer)"
      note_problem "$label: $n_idx indexed lines vs $n_rendered verdict lines"
    fi
  fi

  # ── verdict tokens ─────────────────────────────────────────────────────────
  if [ "$n_idx" -eq 0 ]; then
    field "verdict tokens" "NOT STRUCTURALLY DECIDABLE for the unnumbered"
    cont  "printer — see KNOWN LIMIT in the header"
  else
    local bad
    bad="$(sed -nE 's/^[[:space:]]*\[[[:space:]]*[0-9]+\][[:space:]]*([^[:space:]]+).*/\1/p' "$cap" \
           | grep -vxE 'ok|FAIL' | sort -u | tr '\n' ' ' | sed -E 's/[[:space:]]+$//' || true)"
    if [ -z "${bad:-}" ]; then
      field "every verdict ok|FAIL" "PASS  ($n_idx indexed lines, tokens all in {ok, FAIL})"
    else
      field "every verdict ok|FAIL" "FAIL — unexpected token(s): $bad"
      note_problem "$label: unexpected verdict token(s): $bad"
    fi
  fi

  # ── failures: footer vs body ───────────────────────────────────────────────
  if [ -n "${ff:-}" ]; then
    field "footer failures" "$ff"
    field "rendered failures" "$n_fail"
    if [ "$ff" -eq "$n_fail" ]; then
      field "failures agree" "PASS"
    else
      field "failures agree" "FAIL — footer $ff, body $n_fail"
      note_problem "$label: footer failures $ff != body failures $n_fail"
    fi
  else
    field "footer failures" "UNKNOWN (no footer)"
    field "rendered failures" "$n_fail"
    field "failures agree" "UNKNOWN"
  fi

  # ── exit vs failures ───────────────────────────────────────────────────────
  if [ "$rc" = "UNKNOWN" ]; then
    field "exit agrees w/ failures" "UNKNOWN — RUN-EXITCODES.txt absent or has no"
    cont  "entry for '$key'; not reported as PASS"
    note_problem "$label: exit code unknown"
  elif [ "$rc" -eq 0 ] && [ "$n_fail" -eq 0 ]; then
    field "exit agrees w/ failures" "PASS  (exit 0, 0 rendered failures)"
  elif [ "$rc" -ne 0 ] && [ "$n_fail" -gt 0 ]; then
    field "exit agrees w/ failures" "PASS  (exit $rc, $n_fail rendered failure(s))"
    note_problem "$label: $n_fail rendered failure(s)"
  else
    field "exit agrees w/ failures" "FAIL — exit $rc with $n_fail rendered failure(s)"
    note_problem "$label: exit $rc disagrees with $n_fail rendered failure(s)"
  fi

  # ── protocol refusal vs implementation failure ─────────────────────────────
  local impl_hits impl_first refusal_mentions
  impl_hits="$(grep -vE "$VERDICT_RE" "$cap" | grep -cE "$IMPL_RE" || true)"
  refusal_mentions="$(grep -E "$VERDICT_RE" "$cap" | grep -ciE 'refus' || true)"

  if [ "$impl_hits" -eq 0 ]; then
    field "implementation failure" "NONE — no unhandled condition, backtrace,"
    cont  "debugger banner or compile-time ERROR outside"
    cont  "the verdict lines"
  else
    impl_first="$(grep -vE "$VERDICT_RE" "$cap" | grep -E "$IMPL_RE" | head -1 | cut -c1-88)"
    field "implementation failure" "PRESENT — $impl_hits marker line(s); the suite died"
    cont  "rather than refused. First marker:"
    cont  "| $impl_first"
    note_problem "$label: implementation failure markers present ($impl_hits)"
  fi
  field "typed refusals (info)" "$refusal_mentions verdict line(s) mention a refusal —"
  cont  "a RETAINED refusal is the protocol working and is"
  cont  "never counted as a failure here"
}

i=0
while [ "$i" -lt "${#CAPTURES[@]}" ]; do
  analyse "${LABELS[$i]}" "${CAPTURES[$i]}" "${EXITKEYS[$i]}"
  i=$(( i + 1 ))
done

# ── close ────────────────────────────────────────────────────────────────────
emit ""
if [ "${#PROBLEMS[@]}" -eq 0 ]; then
  emit "RECONCILIATION CLEAN — every derived count agrees with the capture it was"
  emit "derived from. This is arithmetic about a transcript, and nothing more: it"
  emit "is not a pass verdict on Language Form /1, not an audit, and not evidence"
  emit "that the suites test the right things."
else
  emit "RECONCILIATION CRACKED — ${#PROBLEMS[@]} discrepancy/ies:"
  for p in "${PROBLEMS[@]}"; do
    emit "  * $p"
  done
  emit "The raw captures are unfiltered and on disk. Read them; do not patch this"
  emit "artifact."
fi
emit ""
emit "STANDING: Language Form /1 is a CANDIDATE implementation and these captures"
emit "are SELF-CONSISTENCY evidence only. No adoption and no specification freeze"
emit "is implied by this file. Current audit, adoption and freeze standing lives"
emit "in LANGUAGE-FORM-1-RETURN.md, which is the governing record; this artifact"
emit "is not, and deliberately restates none of it."

# ── console ──────────────────────────────────────────────────────────────────
echo ""
echo "  wrote ${OUT#"$HERE"/}"
if [ "${#PROBLEMS[@]}" -eq 0 ]; then
  echo "  RECONCILIATION CLEAN"
  echo ""
  exit 0
else
  echo "  RECONCILIATION CRACKED — ${#PROBLEMS[@]} discrepancy/ies:"
  for p in "${PROBLEMS[@]}"; do
    echo "    * $p"
  done
  echo ""
  exit 1
fi
