;;;; EXPORT-CENSUS.lisp — Language Form /1, Candidate /0.
;;;;
;;;; GENERATES `EXPORT-CENSUS.md` from the LIVE loaded package.
;;;;
;;;; This file exists because a census is worthless without its generator.  Two
;;;; days before this layer was written, this lane docketed a sibling specimen
;;;; for shipping a transcript-check artifact that claimed mechanical generation
;;;; while no generator existed anywhere in the repository (docket D-2).  Every
;;;; number below is derived here, by DO-EXTERNAL-SYMBOLS over the loaded
;;;; package — never by counting export forms, never by arithmetic on a previous
;;;; sentence, and never maintained by hand.
;;;;
;;;; Run: sbcl --non-interactive --load EXPORT-CENSUS.lisp

(unless (find-package :lisp-plus-form1)
  (handler-bind ((style-warning #'muffle-warning))
    (load (merge-pathnames "form1.lisp" *load-truename*))))

(defpackage #:form1-export-census (:use #:cl))
(in-package #:form1-export-census)

(defun classify (name)
  (cond
    ((search "TRY-" name) "try- twin")
    ((member name '("PROPOSE-PETITION" "VALIDATE-PETITION" "MATERIALIZE-PETITION"
                    "SUBMIT-PETITION")
             :test #'string=) "phase transition")
    ((member name '("PETITION-DATUM" "PETITION-HEAD-IDENTIFIER" "SCHEMA-REFERENCE"
                    "CONCLUSION-REFERENCE" "SUPPORT-REFERENCE" "RECEIVER-REFERENCE"
                    "REFERENCE-ROLE")
             :test #'string=) "grammar constructor")
    ((search "BIND-" name) "context binder")
    ((search "RESOLUTION-CONTEXT" name) "context")
    ((search "REFUSAL" name) "refusal surface")
    ((search "REFUSED" name) "refusal surface")
    ((search "SUBMISSION-OUTCOME" name) "submission outcome")
    ((search "SUBMISSION-RECEIPT" name) "submission receipt")
    ((search "MATERIALIZATION-RECEIPT" name) "materialization receipt")
    ((search "VALIDATION-RECEIPT" name) "validation receipt")
    ((search "PROPOSED-PETITION-FORM" name) "proposed reader")
    ((search "VALIDATED-PETITION-FORM" name) "validated reader")
    ((search "DERIVATION-PETITION" name) "petition reader")
    ((search "POLICY" name) "policy identity")
    ((search "GRAMMAR" name) "grammar identity")
    ((search "PROCEDURE" name) "procedure identity")
    ((search "IDENTITY" name) "identity utility")
    (t "other")))

(defun status (symbol)
  (cond ((fboundp symbol) "fbound")
        ((boundp symbol) "bound")
        ((find-class symbol nil) "condition class")
        (t "NEITHER")))

(let ((rows '()) (total 0) (neither 0) (buckets (make-hash-table :test #'equal)))
  (do-external-symbols (symbol :lisp-plus-form1)
    (let* ((name (symbol-name symbol))
           (kind (classify name))
           (state (status symbol)))
      (incf total)
      (when (string= state "NEITHER") (incf neither))
      (incf (gethash kind buckets 0))
      (push (list name kind state) rows)))
  (setf rows (sort rows #'string< :key #'first))
  (with-open-file (out (merge-pathnames "EXPORT-CENSUS.md" *load-truename*)
                       :direction :output :if-exists :supersede
                       :if-does-not-exist :create)
    (format out "# LANGUAGE FORM /1 — CANDIDATE /0 — EXPORT CENSUS~%~%")
    (format out "*Generated by `EXPORT-CENSUS.lisp` from the LIVE loaded package.~%")
    (format out "Do not edit by hand; re-run the generator. Every figure here is~%")
    (format out "derived by `DO-EXTERNAL-SYMBOLS`, not by counting export forms.*~%~%")
    (format out "```~%")
    (format out "live external symbols        ~D~%" total)
    (format out "fbound, bound or a class     ~D~%" (- total neither))
    (format out "neither                      ~D~%" neither)
    (format out "policy version               ~D~%" (lisp-plus-form1:petition-policy-version))
    (format out "grammar version              ~D~%" (lisp-plus-form1:petition-grammar-version))
    ;; REVIEW 1: the flat count is gone.  A single number here could travel
    ;; without the distinction it flattens — three of the codes cannot be
    ;; provoked by any public caller — so the census prints the split.
    (format out "refusal codes, PROTOCOL      ~D   (a public caller can provoke these)~%"
            (length (lisp-plus-form1:petition-protocol-refusal-codes)))
    (format out "refusal codes, INTEGRITY     ~D   (internal guards; NOT publicly reachable)~%"
            (length (lisp-plus-form1:petition-integrity-alarm-codes)))
    (format out "refusal code CATALOGUE       ~D   (the union, reachability stated per code)~%"
            (length (lisp-plus-form1:petition-refusal-code-catalog)))
    (format out "max support references       ~D~%" (lisp-plus-form1:petition-policy-max-support-references))
    (format out "max petition canonical octets ~D~%" (lisp-plus-form1:petition-policy-max-canonical-octets))
    (format out "max identity octets          ~D~%" (lisp-plus-form1:petition-policy-max-identity-octets))
    (format out "outcome tail reserve octets  ~D~%" (lisp-plus-form1:petition-policy-outcome-tail-reserve-octets))
    (format out "```~%~%## By category~%~%| category | symbols |~%|---|---:|~%")
    (let ((keys '()))
      (maphash (lambda (k v) (declare (ignore v)) (push k keys)) buckets)
      (dolist (k (sort keys #'string<))
        (format out "| ~A | ~D |~%" k (gethash k buckets))))
    (format out "~%## Every external symbol~%~%| symbol | category | state |~%|---|---|---|~%")
    (dolist (row rows)
      (format out "| `~A` | ~A | ~A |~%" (first row) (second row) (third row)))
    (format out "~%## Declared refusal codes, BY EVIDENTIARY CLASS~%~%")
    (format out "*Read from `PETITION-REFUSAL-CODE-CATALOG` in the running image.~%")
    (format out "REACHABILITY IS A PUBLISHED COLUMN, not a footnote: a host writing~%")
    (format out "a handler for an `:INTERNAL-PLANTED-FAULT-ONLY` code is writing dead~%")
    (format out "code, and the catalogue is where it can find that out.*~%~%")
    (format out "| code | class | reachability |~%|---|---|---|~%")
    (dolist (entry (lisp-plus-form1:petition-refusal-code-catalog))
      (format out "| `~A` | ~A | `~A` |~%"
              (lisp-plus-form1:petition-refusal-code-entry-code entry)
              (lisp-plus-form1:petition-refusal-code-entry-class entry)
              (lisp-plus-form1:petition-refusal-code-entry-reachability entry)))
    (format out "~%*Whether every one of these is PRODUCED is not this census's~%")
    (format out "question — `form1-selftest.lisp` answers it with live set-differences~%")
    (format out "in both directions, SEPARATELY for each class: protocol codes must be~%")
    (format out "produced through the public API, integrity alarms only under an~%")
    (format out "internal planted fault, and the two produced sets must be disjoint.*~%"))
  (format t "~&EXPORT-CENSUS.md written: ~D externals, ~D neither-fbound-nor-bound~%"
          total neither))
