(load "/tmp/claude-1000/-home-gauss-Desktop-Claude-Code-Lab/d214ea40-d602-4f0d-b684-e6f5fddf4447/scratchpad/surface1-audit/probes/FOSSOR/prelude.lisp")
(in-package #:fossor)
(banner "P3e — THE PUBLIC ENCODE-TERM AND A DEEP-BUT-ACYCLIC CAR CHAIN")
(defun chain (d) (let ((f 0)) (dotimes (i d) (setf f (list f))) f))
(line "the claim under test (surface1.lisp:365-373, ENCODE-TERM docstring):")
(line "  \"Doing it here rather than in the caller is what makes this PUBLIC")
(line "   function safe: in Candidate /0 a CAR-position cycle handed straight to")
(line "   ENCODE-TERM exhausted the control stack instead of refusing.\"")
(format t "~%")
(dolist (d '(1000 10000 20000 30000 40000 60000 100000))
  (let ((outcome
          (handler-case (progn (s1 encode-term (chain d)) "encoded")
            (storage-condition () "CONTROL STACK EXHAUSTED")
            (error (c) (format nil "~S" (type-of c))))))
    (format t "    depth ~7D -> ~A~%" d outcome)))
(banner "P3e2 — WHICH FUNCTION BLOWS: %SHARED-CONS-COUNT, the check itself")
(dolist (d '(20000 40000 100000))
  (format t "    %shared-cons-count at depth ~6D -> ~A~%" d
          (handler-case (format nil "~D" (s1i %shared-cons-count (chain d)))
            (storage-condition () "CONTROL STACK EXHAUSTED"))))
(banner "P3e3 — and the PUBLIC DECODE-TERM on a deep datum built with CD/0 alone")
(defun deep-datum (d)
  (let ((term (s1 encode-term 0)))
    (dotimes (i d)
      (setf term (cd0 make-record-datum
                      (list (cd0 make-record-entry (cd0 make-identifier-datum '("TERM") '("KIND"))
                                 (cd0 make-identifier-datum '("TERMKIND") '("LIST")))
                            (cd0 make-record-entry (cd0 make-identifier-datum '("TERM") '("VALUE"))
                                 (cd0 make-sequence-datum (list term)))))))
    term))
(dolist (d '(100 5000 40000 100000))
  (format t "    decode-term on a ~6D-deep datum -> ~A~%" d
          (handler-case (progn (s1 decode-term (deep-datum d)) "decoded")
            (storage-condition () "CONTROL STACK EXHAUSTED")
            (error (c) (format nil "~S" (type-of c))))))
(banner "P3e4 — THE DETAIL STRING A SATURATED MEASUREMENT PRINTS")
(let* ((x (list 0)))
  (setf (car x) x)
  (let ((r (refusal-of (lambda () (s1 request-expansion (list 'cl:quote x) :macroexpand-1 (tag "sat"))))))
    (line "code ~S" (rcode r))
    (line "detail ~S" (s1 expansion-refusal-detail r))
    (line "upstream-code ~S upstream-category ~S" (rup r) (s1 expansion-refusal-upstream-category r))))
