(load "/tmp/claude-1000/-home-gauss-Desktop-Claude-Code-Lab/d214ea40-d602-4f0d-b684-e6f5fddf4447/scratchpad/surface1-audit/probes/FOSSOR/prelude.lisp")
(in-package #:fossor)
(banner "P3f — THE DETAIL STRING A SATURATED MEASUREMENT PRINTS")
(let ((x (list 0)))
  (setf (car x) x)
  (let ((r (refusal-of (lambda () (s1 request-expansion (list 'cl:quote x) :macroexpand-1 (tag "sat"))))))
    (line "CAR-cycle form: code ~S" (rcode r))
    (line "  detail ...... ~S" (s1 expansion-refusal-detail r))
    (line "  upstream .... code ~S category ~S" (rup r) (s1 expansion-refusal-upstream-category r))))
(let ((x (list 'cl:quote 1 2 3)))
  (setf (cdr (last x)) (cdr x))
  (let ((r (refusal-of (lambda () (s1 request-expansion x :macroexpand-1 (tag "spine"))))))
    (line "spine-cycle form: code ~S" (rcode r))
    (line "  detail ...... ~S" (s1 expansion-refusal-detail r))))
(banner "P3f2 — ENCODE-TERM CONTROL-STACK THRESHOLD (SBCL default 2MB stack)")
(defun chain (d) (let ((f 0)) (dotimes (i d) (setf f (list f))) f))
(defun enc-ok (d) (handler-case (progn (s1 encode-term (chain d)) t) (storage-condition () nil)))
(let ((lo 1000) (hi 40000))
  (loop while (< (+ lo 250) hi)
        do (let ((mid (floor (+ lo hi) 2))) (if (enc-ok mid) (setf lo mid) (setf hi mid))))
  (line "ENCODE-TERM: ok at depth ~D · CONTROL STACK EXHAUSTED at depth ~D" lo hi))
