;;;; prelude.lisp — FOSSOR's image setup.  Loads Surface /1 (which self-loads
;;;; CD/0) from the SUBJECT tree, then Surface /0 separately, as a client.
(defparameter *s1dir*
  (pathname (or (second sb-ext:*posix-argv*)
                "/tmp/claude-1000/-home-gauss-Desktop-Claude-Code-Lab/d214ea40-d602-4f0d-b684-e6f5fddf4447/scratchpad/surface1-audit/extract/target/tree/mneme/language-surface-1/")))
(handler-bind ((style-warning #'muffle-warning))
  (load (merge-pathnames "surface1.lisp" *s1dir*))
  (load (merge-pathnames "../language-surface-0/surface0.lisp" *s1dir*)))
(defpackage #:fossor (:use #:common-lisp))
(in-package #:fossor)
;;; s1 resolves through FIND-SYMBOL and DEMANDS :EXTERNAL — a witness that
;;; reached through INTERN would not be a public-API witness.
(defmacro s1 (name &rest args)
  (multiple-value-bind (sym status) (find-symbol (string name) '#:lisp-plus-surface1)
    (unless (eq status :external)
      (error "S1: ~A is ~S in LISP-PLUS-SURFACE1, not :EXTERNAL" (string name) status))
    `(,sym ,@args)))
;;; s1i reaches an INTERNAL symbol ON PURPOSE, and every use is labelled as such.
(defmacro s1i (name &rest args)
  `(,(or (find-symbol (string name) '#:lisp-plus-surface1)
         (error "internal symbol ~A absent" name)) ,@args))
(defmacro cd0 (name &rest args) `(,(intern (string name) '#:lisp-plus-cd0) ,@args))
(defun tag (&rest path) (cd0 make-identifier-datum '("fossor") path))
(defun same (a b) (cd0 equal-datum a b))
(defun octets-of (d) (cd0 octets-length (cd0 canonical-octets d)))
(defparameter *n* 0)
(defparameter *bad* 0)
(defun line (fmt &rest args) (format t "    ~A~%" (apply #'format nil fmt args)))
(defun banner (s) (format t "~%  ~A~%  ~A~%" s (make-string (length s) :initial-element #\-)))
(defun refusal-of (thunk)
  (handler-case (progn (funcall thunk) nil)
    (lisp-plus-surface1:expansion-refused (c)
      (lisp-plus-surface1:expansion-condition-refusal c))))
(defun rcode (r) (and r (s1 expansion-refusal-code r)))
(defun rphase (r) (and r (s1 expansion-refusal-phase r)))
(defun rcat (r) (and r (s1 expansion-refusal-category r)))
(defun rup (r) (and r (s1 expansion-refusal-upstream-code r)))
(defun catalog-entry (code)
  (find code (s1 expansion-refusal-code-catalog) :key (lambda (e) (s1 refusal-catalog-entry-code e))))
;;; THE ASSERTION: fire CODE and check code+phase+category against the CATALOG.
(defun fires (label code thunk &key (expect-upstream nil))
  (incf *n*)
  (let* ((r (refusal-of thunk))
         (e (catalog-entry code))
         (got (rcode r))
         (okp (and r (eq got code)
                   (eq (rphase r) (s1 refusal-catalog-entry-phase e))
                   (eq (rcat r) (s1 refusal-catalog-entry-class e))
                   (or (null expect-upstream) (equal expect-upstream (rup r))))))
    (unless okp (incf *bad*))
    (format t "  [~2,'0D] ~A  ~A~%       want ~S  got ~S · phase ~S (catalog ~S) · class ~S (catalog ~S)~@[ · upstream ~S~]~%"
            *n* (if okp " MATCH " "MISMATCH") label
            code got (rphase r) (s1 refusal-catalog-entry-phase e)
            (rcat r) (s1 refusal-catalog-entry-class e) (rup r))
    r))
