#!/usr/bin/env bash
#
# teeth.sh — MAKE THE GATE BITE, IN FRONT OF A WITNESS.
#
# ERRATA 0.3 / D4 and D6.  Errata 0.2 wrote that the evidence runner failed closed on
# a truncated run, a renamed label, an early exit and a crash.  It did — for two
# instruments of five.  The claim had never been fired against the other three, and
# the 2026-07-28 stranger audit fired it and found `runner exit = 0` six times over
# (`FOSSOR.md` §4, F4).  A gate you have not seen bite is untested, not passing.
#
# So this script plants faults and RECORDS WHAT THE RUNNER DID.  For every one of the
# SIX instruments it runs five negative controls —
#
#   (a) TRUNCATED at a clean top-level form boundary        — a complete program that
#                                                             stops early; `--load`
#                                                             exits 0
#   (b) ZERO CHECKS RUN, summary re-appended                — the T5/T11 shape: a
#                                                             green summary over an
#                                                             empty run
#   (c) CRASH before the summary                            — real work, then death
#   (d) RENAMED label / TRAILING SPACE on the canonical line — two cases, (d1)/(d2)
#   (e) A REAL CHECK FAILS                                   — a genuine regression,
#                                                             in the instrument or in
#                                                             the subject it measures
#
# — plus a CONTROL (T0, unmutated: the runner must exit 0, or every failure below is
# meaningless), the SUBJECT-DIGEST demonstrations, and the transcript-stability
# demonstration.  EVERY case must end with runner exit 1 EXCEPT T0 and the stability
# runs.  A case that exits 0 is a hole and is reported as one.
#
# NOTHING HERE TOUCHES THE REAL TREE.  A pristine copy of the subject and its whole
# load closure is built once under a scratch directory; each case gets a fresh copy
# of that copy, is mutated, and is thrown away.
#
# Usage:  bash teeth.sh [--only PREFIX] [--keep]
set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
S1="$(cd "$HERE/../.." && pwd)"          # …/mneme/language-surface-1
LL="$(cd "$S1/../.." && pwd)"            # …/experiments/latent-lisp
MUTATE="$HERE/mutate.py"

ONLY=""
KEEP=0
while [ $# -gt 0 ]; do
  case "$1" in
    --only) ONLY="$2"; shift 2 ;;
    --keep) KEEP=1; shift ;;
    *) echo "teeth.sh: unknown argument $1" >&2; exit 2 ;;
  esac
done

WORK="$(mktemp -d /tmp/surface1-teeth.XXXXXXXX)" || exit 2
MASTER="$WORK/master"
trap '[ "$KEEP" -eq 1 ] || rm -rf "$WORK"' EXIT

echo "teeth.sh: scratch root $WORK"

# --- the pristine copy: the subject and its ENTIRE traced load closure -----
mkdir -p "$MASTER/canonical-datum/common-lisp" "$MASTER/mneme"
cp "$LL/canonical-datum/common-lisp/package.lisp" "$MASTER/canonical-datum/common-lisp/"
cp "$LL/canonical-datum/common-lisp/cd0.lisp"     "$MASTER/canonical-datum/common-lisp/"
for d in kernel0 language-core-0 language-slice-0 language-slice-1 \
         language-slice-2 language-surface-0; do
  cp -a "$LL/mneme/$d" "$MASTER/mneme/"
done
cp -a "$S1" "$MASTER/mneme/language-surface-1"
# the audit's immutable evidence is not needed to run anything and is bulky
rm -rf "$MASTER/mneme/language-surface-1/audits"
rm -f  "$MASTER/mneme/language-surface-1/errata-0.3/teeth/OUT-"*.txt

SUMMARY="$HERE/SUMMARY.txt"
: > "$SUMMARY"
say() { printf '%s\n' "$*" | tee -a "$SUMMARY"; }

say "SURFACE /1 ERRATA 0.3 — RUNNER TEETH"
say "generated by errata-0.3/teeth/teeth.sh; every line below is an OBSERVED exit code"
say "host SBCL: $(sbcl --non-interactive --eval '(progn (princ (lisp-implementation-version))(terpri))' 2>/dev/null | tail -1)"
say ""
printf '%-34s %-22s %-8s %-8s %s\n' "case" "instrument" "expect" "observed" "verdict" | tee -a "$SUMMARY"
printf '%-34s %-22s %-8s %-8s %s\n' "----" "----------" "------" "--------" "-------" | tee -a "$SUMMARY"

HOLES=0
run_case() {
  local name="$1" instrument="$2" expect="$3" mutation="$4"
  if [ -n "$ONLY" ] && [[ "$name" != "$ONLY"* ]]; then return; fi
  rm -rf "$WORK/case"
  cp -a "$MASTER" "$WORK/case"
  local T="$WORK/case/mneme/language-surface-1"
  local out="$HERE/OUT-${name}.txt"
  {
    echo "=== CASE ${name} — ${instrument}"
    echo "=== MUTATION: ${mutation}"
    ( cd "$T" && eval "$mutation" ) 2>&1
    echo "=== RUNNER OUTPUT"
  } > "$out"
  ( cd "$T" && bash run-surface1-candidate.sh ) >> "$out" 2>&1
  local exit_code=$?
  {
    echo "=== RUNNER EXIT ${exit_code}"
    echo "=== WHAT EACH INSTRUMENT ACTUALLY PRINTED AS ITS CANONICAL LINE"
    echo "    (an exit code says THAT something refused; this says WHAT was refused)"
    for f in RUN-SELFTEST.txt RUN-STUB-IMAGE.txt RUN-APPLICATION.txt \
             RUN-REPRODUCTION.txt RUN-REPRODUCTION-II.txt RUN-REPRODUCTION-III.txt; do
      local printed
      printed="$(grep -E '^[A-Z0-9-]*RESULTS? ' "$T/$f" 2>/dev/null | tail -1)"
      printf '    %-26s %s\n' "$f" "${printed:-(NO CANONICAL LINE PRINTED)}"
    done
    echo "=== RUN-EXITCODES.txt"
    cat "$T/RUN-EXITCODES.txt" 2>/dev/null || echo "(absent)"
  } >> "$out"
  local verdict="BITES"
  if [ "$exit_code" != "$expect" ]; then verdict="*** HOLE ***"; HOLES=$((HOLES+1)); fi
  printf '%-34s %-22s %-8s %-8s %s\n' "$name" "$instrument" "$expect" "$exit_code" "$verdict" \
    | tee -a "$SUMMARY"
}

# ---------------------------------------------------------------------------
# T0 — THE CONTROL.  If this is not 0, nothing below means anything.
run_case "T0-control" "all six" 0 "true"

# ---------------------------------------------------------------------------
# (a) TRUNCATED AT A CLEAN TOP-LEVEL FORM BOUNDARY
run_case "T1a-selftest-truncated"  "selftest"     1 "python3 $MUTATE cut surface1-selftest.lisp 0.6"
run_case "T1b-stub-truncated"      "stub fixture" 1 "python3 $MUTATE cut STUB-IMAGE-FIXTURE.lisp 0.6"
run_case "T1c-application-truncated" "application" 1 "python3 $MUTATE cut de-expansione-testata/APPLICATION.lisp 0.6"
run_case "T1d-repro1-truncated"    "reproduction I"   1 "python3 $MUTATE cut errata-0.1/REPRODUCTION.lisp 0.6"
run_case "T1e-repro2-truncated"    "reproduction II"  1 "python3 $MUTATE cut errata-0.2/REPRODUCTION-II.lisp 0.6"
run_case "T1f-repro3-truncated"    "reproduction III" 1 "python3 $MUTATE cut errata-0.3/REPRODUCTION-III.lisp 0.6"

# ---------------------------------------------------------------------------
# (b) ZERO CHECKS RUN, THE SUMMARY RE-APPENDED — the shape that scored 0/0 green
run_case "T2a-selftest-zero-checks" "selftest"     1 "python3 $MUTATE zero surface1-selftest.lisp 'defparameter [*]expected-checks[*]'"
run_case "T2b-stub-zero-checks"     "stub fixture" 1 "python3 $MUTATE zero STUB-IMAGE-FIXTURE.lisp 'defparameter [*]failed[*]'"
run_case "T2c-application-zero-checks" "application" 1 "python3 $MUTATE zero de-expansione-testata/APPLICATION.lisp 'defparameter [*]failed[*]'"
run_case "T2d-repro1-zero-verdicts" "reproduction I"   1 "python3 $MUTATE zero errata-0.1/REPRODUCTION.lisp 'defparameter [*]verdicts[*]'"
run_case "T2e-repro2-zero-verdicts" "reproduction II"  1 "python3 $MUTATE zero errata-0.2/REPRODUCTION-II.lisp 'defparameter [*]verdicts[*]'"
run_case "T2f-repro3-zero-verdicts" "reproduction III" 1 "python3 $MUTATE zero errata-0.3/REPRODUCTION-III.lisp 'defparameter [*]reclassified[*]'"

# ---------------------------------------------------------------------------
# (c) CRASH BEFORE THE SUMMARY
run_case "T3a-selftest-crash"    "selftest"     1 "python3 $MUTATE crash surface1-selftest.lisp 0.6"
run_case "T3b-stub-crash"        "stub fixture" 1 "python3 $MUTATE crash STUB-IMAGE-FIXTURE.lisp 0.6"
run_case "T3c-application-crash" "application"  1 "python3 $MUTATE crash de-expansione-testata/APPLICATION.lisp 0.6"
run_case "T3d-repro1-crash"      "reproduction I"   1 "python3 $MUTATE crash errata-0.1/REPRODUCTION.lisp 0.6"
run_case "T3e-repro2-crash"      "reproduction II"  1 "python3 $MUTATE crash errata-0.2/REPRODUCTION-II.lisp 0.6"
run_case "T3f-repro3-crash"      "reproduction III" 1 "python3 $MUTATE crash errata-0.3/REPRODUCTION-III.lisp 0.6"

# ---------------------------------------------------------------------------
# (d1) THE CANONICAL LABEL RENAMED
run_case "T4a-selftest-renamed"    "selftest"     1 "python3 $MUTATE rename surface1-selftest.lisp"
run_case "T4b-stub-renamed"        "stub fixture" 1 "python3 $MUTATE rename STUB-IMAGE-FIXTURE.lisp"
run_case "T4c-application-renamed" "application"  1 "python3 $MUTATE rename de-expansione-testata/APPLICATION.lisp"
run_case "T4d-repro1-renamed"      "reproduction I"   1 "python3 $MUTATE rename errata-0.1/REPRODUCTION.lisp"
run_case "T4e-repro2-renamed"      "reproduction II"  1 "python3 $MUTATE rename errata-0.2/REPRODUCTION-II.lisp"
run_case "T4f-repro3-renamed"      "reproduction III" 1 "python3 $MUTATE rename errata-0.3/REPRODUCTION-III.lisp"

# ---------------------------------------------------------------------------
# (d2) ONE TRAILING SPACE ON THE CANONICAL LINE
run_case "T5a-selftest-trailspace"    "selftest"     1 "python3 $MUTATE trailspace surface1-selftest.lisp"
run_case "T5b-stub-trailspace"        "stub fixture" 1 "python3 $MUTATE trailspace STUB-IMAGE-FIXTURE.lisp"
run_case "T5c-application-trailspace" "application"  1 "python3 $MUTATE trailspace de-expansione-testata/APPLICATION.lisp"
run_case "T5d-repro1-trailspace"      "reproduction I"   1 "python3 $MUTATE trailspace errata-0.1/REPRODUCTION.lisp"
run_case "T5e-repro2-trailspace"      "reproduction II"  1 "python3 $MUTATE trailspace errata-0.2/REPRODUCTION-II.lisp"
run_case "T5f-repro3-trailspace"      "reproduction III" 1 "python3 $MUTATE trailspace errata-0.3/REPRODUCTION-III.lisp"

# ---------------------------------------------------------------------------
# (e) A REAL CHECK INSIDE THE INSTRUMENT FAILS.
# Two flavours, both real: an instrument-side flip where the instrument owns the
# proposition, and a SUBJECT-side regression where the instrument's whole job is to
# notice one.  The subject-side cases are the more valuable: they are the standing
# regression gate doing the work it exists for.
run_case "T6a-selftest-check-fails" "selftest" 1 \
  "sed -i 's/(= 48 (s1 expansion-policy-max-source-depth))/(= 47 (s1 expansion-policy-max-source-depth))/' surface1-selftest.lisp"
run_case "T6b-stub-check-fails" "stub fixture" 1 \
  "sed -i 's/:construct-not-a-macro (s1 expansion-refusal-code refusal)/:no-such-refusal-code (s1 expansion-refusal-code refusal)/' STUB-IMAGE-FIXTURE.lisp"
# The application case fires the check that REPLACED the F-1 tautology: shrink the
# abbreviation window until two distinct identities print the same way.  The old
# check could not have noticed; this one must.
run_case "T6c-application-check-fails" "application" 1 \
  "python3 $MUTATE collide de-expansione-testata/APPLICATION.lisp"
# Reproduction I finding 4 is a claim about EXPORT STATUS.  Un-export the accessor in
# the subject and the finding must CONFIRM again — the repaired two-sided predicate
# is what makes this detectable at all.
run_case "T6d-repro1-subject-regressed" "reproduction I" 1 \
  "sed -i 's/^   #:refusal-catalog-entry-reachability/   ;; UN-EXPORTED BY TEETH/' package.lisp"
# Reproduction II finding A is a claim about the home-package conjunct.  Neuter it in
# the subject and the inherited-symbol substitution comes back.
run_case "T6e-repro2-subject-regressed" "reproduction II" 1 \
  "sed -i 's/(eq (symbol-package symbol) package))/t)/' surface1.lisp"
# Reproduction III's D1 verdicts are CLASSIFICATION verdicts.  Put the retracted
# reachability claim back in the catalogue and they must CONFIRM again.
run_case "T6f-repro3-subject-regressed" "reproduction III" 1 \
  "sed -i 's/(:expanded-nodes-exceeded       :protocol-refusal :perform :public-api/(:expanded-nodes-exceeded       :protocol-refusal :perform :unreachable-under-this-policy/' surface1.lisp"

# ---------------------------------------------------------------------------
# THE MEASURING APPARATUS ITSELF FAILS CLOSED.  A digest that could not be computed
# must stop the run, not default to something reassuring.
run_case "T7a-manifest-member-deleted" "digest (runner)"  2 "rm -f ../kernel0/folds.lisp"
run_case "T7b-manifest-deleted"        "digest (runner)"  2 "rm -f errata-0.3/SUBJECT-MANIFEST.txt"
run_case "T7c-digest-script-deleted"   "digest (runner)"  2 "rm -f errata-0.3/subject-digest.sh"
run_case "T7d-evidence-lisp-deleted"   "digest (runner)"  2 "rm -f errata-0.3/EVIDENCE.lisp"
run_case "T7e-repro3-absent"           "runner required"  2 "rm -f errata-0.3/REPRODUCTION-III.lisp"
run_case "T7f-manifest-names-a-transcript" "digest (runner)" 2 \
  "printf 'RUN-SELFTEST.txt\n' >> errata-0.3/SUBJECT-MANIFEST.txt"

say ""
if [ "$HOLES" -eq 0 ]; then
  say "RESULT: every planted fault was refused.  0 holes."
else
  say "RESULT: *** ${HOLES} HOLE(S) *** — a case did not produce the expected exit."
fi
say ""
say "Per-case transcripts: errata-0.3/teeth/OUT-<case>.txt (runner banner, exit code,"
say "and the RUN-EXITCODES.txt block showing WHICH instrument's gate refused)."
exit 0
