;;;; de-monadibus.lisp — On windowless evaluators
;;;;
;;;; Run from this directory with:
;;;;   sbcl --script de-monadibus.lisp

(load (merge-pathnames "../src/package.lisp" *load-truename*))
(load (merge-pathnames "../src/core.lisp" *load-truename*))

(in-package #:leibnitiana)

(defun cup-law (state tick)
  "The cup knows only its own phase and the common logical tick."
  (let ((phase (cond ((< tick 3) :resting)
                     ((= tick 3) :falling)
                     (t :broken))))
    (values (list :phase phase :previous state)
            phase)))

(defun witness-law (state tick)
  "The witness has no reference to the cup, yet its history corresponds."
  (declare (ignore state))
  (let ((hearing (cond ((< tick 3) :silence)
                       ((= tick 3) :impact)
                       (t :aftermath))))
    (values (list :hearing hearing)
            hearing)))

(let ((cup (make-monad :cup '(:phase :resting) #'cup-law))
      (witness (make-monad :witness '(:hearing :silence) #'witness-law)))
  (print-section "PRE-ESTABLISHED HARMONY AS SCHEDULER SEMANTICS")
  (run-harmony (list cup witness) '(0 1 2 3 4))

  (print-section "BOUNDARY OF THE DEMONSTRATION")
  (format t "The two closures never receive one another. Their correspondence is generated by independent laws over a shared tick.~%")
  (format t "But the scheduler sees both, chooses the tick, and prints the whole scene. God has not vanished; God has become orchestration infrastructure.~%"))
