;;;; probe-D.lisp — the declared depth-edge numbers (201 / 64 / 63 / ~2.03).
(defparameter *s1dir*
  (pathname "/tmp/claude-1000/-home-gauss-Desktop-Claude-Code-Lab/d214ea40-d602-4f0d-b684-e6f5fddf4447/scratchpad/surface1-audit/extract/target/tree/mneme/language-surface-1/"))
(handler-bind ((style-warning #'muffle-warning))
  (load (merge-pathnames "surface1.lisp" *s1dir*)))
(defpackage #:tabd (:use #:common-lisp)) (in-package #:tabd)
(defmacro s1 (n &rest a) `(,(find-symbol (string n) '#:lisp-plus-surface1) ,@a))
(defmacro cd0 (n &rest a) `(,(find-symbol (string n) '#:lisp-plus-cd0) ,@a))
(defun L (c &rest a) (format t "~&~A~%" (apply #'format nil c a)))
(defun nest (n) (let ((f 'cl:t)) (dotimes (i n) (setf f (list f))) f))
(defun encodes-p (n) (handler-case (progn (s1 encode-term (nest n)) t) (error () nil)))
(defun decodes-p (n)
  (handler-case (let ((d (s1 encode-term (nest n))))
                  (cd0 decode-exact (cd0 canonical-octets d)) t)
    (error () nil)))
(L "=== package.lisp: 'a host form nested 201 levels encodes without complaint' ===")
(L "encode(201-nested) ......... ~A" (encodes-p 201))
(L "encode(500-nested) ......... ~A" (encodes-p 500))
(L "=== 'refuses on decode at 64' / 'largest that both encodes and decodes is 63' ===")
(let ((last-ok nil) (first-bad nil))
  (loop for n from 55 to 75
        do (let ((d (decodes-p n)))
             (when (and d (or (null last-ok) (> n last-ok))) (setf last-ok n))
             (when (and (not d) (null first-bad)) (setf first-bad n))))
  (L "largest host nesting that DECODES ... ~D" last-ok)
  (L "smallest that does NOT decode ...... ~D" first-bad))
(L "=== CD/0 depth cost per host list level ===")
(L "cd0 max-depth constant present? ~A"
   (let ((s (find-symbol "MAX-DEPTH" '#:lisp-plus-cd0))) (and s (if (fboundp s) (funcall s) (and (boundp s) (symbol-value s))))))
