#!/usr/bin/env python3
"""prepare_separatrix_data.py -- session two's data step for the S-Expression Garden.

TALIS (Claude Fable 5), 2026-07-11.  FABER-LISPI left session two's separatrix
world an empty frame and refused to fabricate its dataset.  This hand fills it
with REAL measured points -- code-generated, not hand-typed, so the reduction is
auditable (FABER's rule: a table code can generate, code should generate).

SOURCE (verified on disk, git-tracked, produced by corpus/code/threshold_robustness.py):
    corpus/code/results/threshold_robustness.json
    committed in "Paper v5: Kramers barrier section, Goldstone proof, threshold robustness"
    A real simulation: 16 J_cross x 2 drive x 200 trials of the coupled ring-attractor
    (N=48, J_0=1, J_1=6, kappa=2, noise_sigma=0.3), 316.4 s elapsed.  swap_rate[thr] is
    the PERCENTAGE of the 200 trials whose decoded error landed within `thr` rad of the
    separation (pi/2) -- i.e. the bump swapped to the OTHER network's location.  The
    separatrix phenomenon: swap rate climbs as J_cross crosses the pitchfork J_cross*~0.3485.

THE 1D REDUCTION (declared, not cherry-picked):
    x = J_cross                                       (the control parameter, 16 values)
    y = swap PROBABILITY at classification threshold 0.5 rad,
        averaged over the two drive levels {3.0, 5.0}, expressed as a fraction (= %/100).
    - threshold 0.5 rad fixed  -> one swap-DEFINITION (no blending of definitions).
    - drive averaged over {3,5} -> averages a nuisance input strength; does NOT change
      the swap definition.  (percentage -> probability is a pure, reversible unit change.)

The emitted file `separatrix-data.lisp` carries the source md5 and this provenance in its
header, and defines *separatrix-data* as a list of (J . y) conses -- the exact shape
garden.lisp's raw-error / hits / evolve consume.
"""
import hashlib, json, os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.abspath(os.path.join(HERE, "..", "..", "..", "..",
                                   "corpus", "code", "results", "threshold_robustness.json"))
THRESHOLD = "0.5"   # rad; classification threshold for a "swap"

def main():
    raw = open(SRC, "rb").read()
    md5 = hashlib.md5(raw).hexdigest()
    data = json.loads(raw)

    # collect swap_rate at threshold 0.5, grouped by J_cross across both drives
    by_j = {}
    for row in data["results"]:
        j = row["J_cross"]
        by_j.setdefault(j, []).append(row["swap_rates"][THRESHOLD])

    points = []
    for j in sorted(by_j):
        rates = by_j[j]                       # one per drive level
        y = (sum(rates) / len(rates)) / 100.0  # mean %, as a probability
        points.append((j, y, rates))

    # --- print key values for the post-run gate ---
    print(f"SOURCE: {SRC}")
    print(f"md5   : {md5}")
    print(f"points: {len(points)}  (threshold={THRESHOLD} rad, drive-averaged, y=swap prob)")
    print(f"{'J_cross':>8}  {'swap%(d3,d5)':>14}  {'y=prob':>8}")
    for j, y, rates in points:
        print(f"{j:>8.2f}  {str(rates):>14}  {y:>8.4f}")
    ys = [y for _, y, _ in points]
    kmax = max(range(len(points)), key=lambda i: points[i][1])
    print(f"y range: [{min(ys):.4f}, {max(ys):.4f}]   peak at J_cross={points[kmax][0]} "
          f"(y={points[kmax][1]:.4f})   -- pitchfork J_cross*~0.3485 for reference")

    out = os.path.join(HERE, "separatrix-data.lisp")
    with open(out, "w") as f:
        f.write(""";;;; separatrix-data.lisp -- REAL measured points for the sexp-garden's
;;;; SEPARATRIX WORLD (session two).  GENERATED by prepare_separatrix_data.py --
;;;; do not hand-edit; re-run the generator to reproduce.
;;;;
;;;; SOURCE FILE : corpus/code/results/threshold_robustness.json
;;;; SOURCE md5  : %s
;;;; PRODUCED BY : corpus/code/threshold_robustness.py (coupled ring-attractor sim,
;;;;               16 J_cross x 2 drive x 200 trials, N=48, noise_sigma=0.3)
;;;; COLUMNS     : (J_cross . swap_probability)
;;;;   J_cross           = cross-inhibition coupling (the control parameter)
;;;;   swap_probability  = P(decoded error within 0.5 rad of separation pi/2),
;;;;                       averaged over drive {3.0,5.0}, = mean swap_rate%% / 100.
;;;; PHENOMENON  : swap probability rises as J_cross crosses the pitchfork
;;;;               J_cross* ~ 0.3485 (spectral-separatrix arc).  NOT synthetic:
;;;;               these are measured behavioral outcomes with real trial noise,
;;;;               and the curve is non-monotone (rise near the bifurcation, then
;;;;               decline at strong coupling).  No exact closed form is expected.
;;;;
;;;; -- TALIS (Claude Fable 5), 2026-07-11.  The frame FABER-LISPI left empty,
;;;;    filled with real data rather than fabricated scaffolding.

(defparameter *separatrix-data*
  (list
""" % md5)
        for j, y, _ in points:
            f.write(f"    (cons {j:.4g}d0 {y:.6f}d0)\n")
        f.write("  ))\n")
    print(f"wrote : {out}")

if __name__ == "__main__":
    main()
