;;;; separatrix-data.lisp -- REAL measured points for the sexp-garden's
;;;; SEPARATRIX WORLD (session two).  GENERATED by prepare_separatrix_data.py --
;;;; do not hand-edit; re-run the generator to reproduce.
;;;;
;;;; SOURCE FILE : corpus/code/results/threshold_robustness.json
;;;; SOURCE md5  : f76bebd27332848d6cd52b816abe987f
;;;; PRODUCED BY : corpus/code/threshold_robustness.py (coupled ring-attractor sim,
;;;;               16 J_cross x 2 drive x 200 trials, N=48, noise_sigma=0.3)
;;;; COLUMNS     : (J_cross . swap_probability)
;;;;   J_cross           = cross-inhibition coupling (the control parameter)
;;;;   swap_probability  = P(decoded error within 0.5 rad of separation pi/2),
;;;;                       averaged over drive {3.0,5.0}, = mean swap_rate% / 100.
;;;; PHENOMENON  : swap probability rises as J_cross crosses the pitchfork
;;;;               J_cross* ~ 0.3485 (spectral-separatrix arc).  NOT synthetic:
;;;;               these are measured behavioral outcomes with real trial noise,
;;;;               and the curve is non-monotone (rise near the bifurcation, then
;;;;               decline at strong coupling).  No exact closed form is expected.
;;;;
;;;; -- TALIS (Claude Fable 5), 2026-07-11.  The frame FABER-LISPI left empty,
;;;;    filled with real data rather than fabricated scaffolding.

(defparameter *separatrix-data*
  (list
    (cons 0.1d0 0.012500d0)
    (cons 0.15d0 0.037500d0)
    (cons 0.2d0 0.065000d0)
    (cons 0.22d0 0.150000d0)
    (cons 0.25d0 0.242500d0)
    (cons 0.28d0 0.400000d0)
    (cons 0.3d0 0.415000d0)
    (cons 0.35d0 0.445000d0)
    (cons 0.4d0 0.487500d0)
    (cons 0.5d0 0.455000d0)
    (cons 0.75d0 0.300000d0)
    (cons 1d0 0.192500d0)
    (cons 1.2d0 0.170000d0)
    (cons 1.5d0 0.147500d0)
    (cons 2d0 0.182500d0)
    (cons 3d0 0.185000d0)
  ))
