;;;; adapter0-l17.lisp — the §25 L17 route audit, executed and emitted as
;;;; a conformance ARTIFACT (AP-ERG-3: never prose reassurance).
;;;;
;;;; Run:  sbcl --script mneme/adapter0/adapter0-l17.lisp
;;;; from the latent-lisp root.  Exit 0 iff every check passed.  Writes
;;;; mneme/adapter0/L17-ROUTE-AUDIT-ARTIFACT.md deterministically from
;;;; live data (the operation surface + the frozen registry) — the
;;;; artifact is code-generated, byte-stable, and re-derived on every run.
;;;;
;;;; — CLAVIGER-IV (Claude Fable 5 subagent), 2026-07-30

(load (merge-pathnames "load.lisp"
                       (make-pathname :name nil :type nil
                                      :defaults *load-truename*)))

(in-package #:lisp-plus-adapter0)

(defvar *checks* 0)
(defvar *failures* 0)

(defun check (description thunk)
  (incf *checks*)
  (let ((description (format nil description))
        (outcome (handler-case (if (funcall thunk) :ok :fail)
                   (error (condition) (list :error condition)))))
    (if (eq outcome :ok)
        (format t "[L~3,'0d] ok   ~a~%" *checks* description)
        (progn (incf *failures*)
               (format t "[L~3,'0d] FAIL ~a~@[ (~a)~]~%" *checks* description
                       (when (consp outcome) (second outcome)))))))

(defun note (control &rest arguments)
  (apply #'format t control arguments)
  (terpri))

(note "adapter0-l17 — the mechanical route audit (AP-ERG-1/2/3)")

(check "the lawful route to a projected manifestation is 4 public API ~
        actions (prepare-invocation → dispatch → await-terminal → ~
        project-envelope) — the exact figure every frozen vector ~
        declares as lawful-route-steps"
  (lambda ()
    (and (= 4 (length (lawful-route-actions)))
         (every (lambda (entry)
                  (let ((case-record (read-pjs-fixture
                                      (merge-pathnames
                                       (registry-entry-path entry)
                                       +reissue-root+))))
                    (eql 4 (case-integer case-record "lawful-route-steps"))))
                (registry-entries)))))

(check "no supported bypass exists: the twelve-operation surface returns ~
        typed records/handles/markers only (AP-OP-2) and provides NO raw ~
        provider call (AP-ERG-2 honored by absence — raw escape is not ~
        merely discouraged, it is not offered)"
  (lambda ()
    (and (= 12 (length +operation-surface+))
         ;; The one frozen bypass fixture declares a 1-step bypass and is
         ;; REJECTED by the validator (AP-ERG-1's teeth).
         (multiple-value-bind (verdict condition)
             (validate-case (read-pjs-fixture
                             (merge-pathnames
                              "vectors/adversarial/BAD-ERG-01.pjs"
                              +reissue-root+)))
           (and (eq verdict :reject)
                (equal condition "adapter-truth-minting"))))))

(check "AP-ERG-1 holds vacuously-with-evidence: supported bypass count ~
        is 0, so no supported route is shorter than the lawful one; the ~
        comparison is recorded row-by-row in the artifact"
  (lambda ()
    (>= (length (l17-route-audit-lines)) 14)))

;;; ---------------------------------------------------------------------------
;;; Emit the artifact (deterministic; derived from live data only).

(defvar *artifact-path* #p"mneme/adapter0/L17-ROUTE-AUDIT-ARTIFACT.md")

(with-open-file (stream *artifact-path* :direction :output
                                        :if-exists :supersede
                                        :if-does-not-exist :create)
  (format stream "# L17-ROUTE-AUDIT-ARTIFACT — Adapter /0~%~%")
  (format stream "Generated by `mneme/adapter0/adapter0-l17.lisp` from ~
                  live data (the §20 operation surface and the frozen ~
                  registry); re-derived deterministically on every run ~
                  (AP-ERG-3: an artifact, not prose reassurance).~%~%")
  (format stream "## The comparison (AP-ERG-1)~%~%")
  (format stream "| Route | Public API actions | Steps |~%|---|---|---:|~%")
  (format stream "| shortest documented lawful route | ~{`~a`~^ → ~} | ~a |~%"
          (lawful-route-actions) (length (lawful-route-actions)))
  (format stream "| supported bypass / convenience routes | none offered ~
                  — every operation returns a typed record, handle, or ~
                  marker (AP-OP-2); no raw provider call exists ~
                  (AP-ERG-2) | 0 routes |~%~%")
  (format stream "Verdict: with zero supported bypass routes, no ~
                  supported route is shorter than the lawful route.  The ~
                  one frozen bypass scenario (BAD-ERG-01, declared ~
                  bypass-route-steps 1 < lawful 4) is REJECTED by the ~
                  validator with `adapter-truth-minting`.~%~%")
  (format stream "## Per-operation semantic obligations~%~%")
  (format stream "| Operation | Class | Carries |~%|---|---|---|~%")
  (loop for (name class) in +operation-surface+
        do (format stream "| `~a` | ~a | receipts · identities · evidence ~
                           · exposure · journal state · outcome context |~%"
                   name (string-downcase (symbol-name class))))
  (format stream "~%## Registry cross-check~%~%")
  (format stream "Every one of the ~a registered vectors declares ~
                  `lawful-route-steps` = 4, matching the implemented ~
                  lawful route's length.~%"
          (length (registry-entries)))
  (format stream "~%*— CLAVIGER-IV (Claude Fable 5), generated artifact; ~
                  edit the generator, not this file.*~%"))

(check "the artifact file was written and carries the lawful-route row ~
        and the twelve operation rows"
  (lambda ()
    (with-open-file (stream *artifact-path* :direction :input)
      (let ((text (make-string (file-length stream))))
        (read-sequence text stream)
        (and (search "shortest documented lawful route" text)
             (search "`project-envelope`" text)
             (search "adapter-truth-minting" text))))))

(format t "~%adapter0-l17: ~a check~:p, ~a failure~:p~%"
        *checks* *failures*)
(if (zerop *failures*)
    (progn (format t "RESULT: PASS~%") (sb-ext:exit :code 0))
    (progn (format t "RESULT: FAIL~%") (sb-ext:exit :code 1)))
