(in-package #:lisp-plus-lci0)

(defun %scope-expression (scope) (record-field-named scope "expression"))
(defun %scope-form (scope) (exact-form-name (%scope-expression scope)))

(defun %datum-sequence-list (sequence)
  (unless (sequence-datum-p sequence) (return-from %datum-sequence-list nil))
  (loop for index below (sequence-datum-length sequence)
        collect (sequence-datum-ref sequence index)))

(defun %datum-member-p (datum list)
  (some (lambda (item) (equal-datum datum item)) list))

(defun %datum-subset-p (left right)
  (every (lambda (item) (%datum-member-p item right)) left))

(defun %scope-object (scope name)
  (record-field-named (%scope-expression scope) name))

(defun %same-calculus-p (left right)
  (equal-datum (record-field-named left "calculus")
               (record-field-named right "calculus")))

(defun %relation-id (name)
  (make-id '("lisp-plus" "lci" "0" "relation") (list name)))

(defun scope-relation (left right)
  (validate-scope left :path '("left"))
  (validate-scope right :path '("right"))
  (unless (%same-calculus-p left right)
    (lci-fail "relation-undetermined" "ScopeIncompatible" "target-relation"
              :path '("right")))
  (when (equal-datum left right)
    (return-from scope-relation (%relation-id "equal")))
  (let ((lf (%scope-form left)) (rf (%scope-form right)))
    (cond
      ((or (string= lf "symbolic-predicate")
           (string= rf "symbolic-predicate"))
       (lci-fail "relation-undetermined" "ScopeRelationUnknown" "target-relation"
                 :path '("right")))
      ((string= lf "universal") (%relation-id "wider"))
      ((string= rf "universal") (%relation-id "narrower"))
      ((and (string= lf "organization")
            (member rf '("department" "tenant") :test #'string=)
            (equal-datum (%scope-object left "organization")
                         (%scope-object right "organization")))
       (%relation-id "wider"))
      ((and (string= rf "organization")
            (member lf '("department" "tenant") :test #'string=)
            (equal-datum (%scope-object left "organization")
                         (%scope-object right "organization")))
       (%relation-id "narrower"))
      ((and (string= lf "region-set") (string= rf "region-set"))
       (let ((lset (%datum-sequence-list (%scope-object left "members")))
             (rset (%datum-sequence-list (%scope-object right "members"))))
         (cond ((and (%datum-subset-p rset lset)
                     (not (%datum-subset-p lset rset))) (%relation-id "wider"))
               ((and (%datum-subset-p lset rset)
                     (not (%datum-subset-p rset lset))) (%relation-id "narrower"))
               ((some (lambda (item) (%datum-member-p item rset)) lset)
                (%relation-id "overlap"))
               (t (%relation-id "disjoint")))))
      ((and (member lf '("department" "tenant") :test #'string=)
            (string= lf rf))
       (%relation-id "disjoint"))
      ((and (string= lf "opaque-token") (string= rf "opaque-token"))
       (%relation-id "disjoint"))
      (t (%relation-id "disjoint")))))

(defun %temporal-model (time) (record-field-named time "temporal-model"))
(defun %temporal-expression (time) (record-field-named time "expression"))
(defun %temporal-form (time) (exact-form-name (%temporal-expression time)))
(defun %temporal-int (time name)
  (integer-datum-value (record-field-named (%temporal-expression time) name)))
(defun %temporal-bool (time name)
  (boolean-datum-value (record-field-named (%temporal-expression time) name)))

(defun %interval-view (time)
  (let ((form (%temporal-form time)))
    (cond ((string= form "instant")
           (let ((tick (%temporal-int time "tick")))
             (list tick tick t t :instant)))
          ((string= form "interval")
           (list (%temporal-int time "start") (%temporal-int time "end")
                 (%temporal-bool time "start-closed")
                 (%temporal-bool time "end-closed") :interval))
          (t nil))))

(defun %endpoint-before-p (left-end left-closed right-start right-closed)
  (or (< left-end right-start)
      (and (= left-end right-start) (not (and left-closed right-closed)))))

(defun %interval-contains-p (outer inner)
  (destructuring-bind (os oe osc oec &rest ignore) outer
    (declare (ignore ignore))
    (destructuring-bind (is ie isc iec &rest ignore2) inner
      (declare (ignore ignore2))
      (and (or (< os is) (and (= os is) (or osc (not isc))))
           (or (> oe ie) (and (= oe ie) (or oec (not iec))))))))

(defun temporal-relation (left right)
  (validate-subject-time left :path '("left"))
  (validate-subject-time right :path '("right"))
  (unless (equal-datum (%temporal-model left) (%temporal-model right))
    (lci-fail "relation-undetermined" "UnsupportedTemporalModel" "subject-time"
              :path '("right" "temporal-model")))
  (when (equal-datum left right)
    (return-from temporal-relation (%relation-id "equal")))
  (let ((lf (%temporal-form left)) (rf (%temporal-form right)))
    (when (or (string= lf "symbolic") (string= rf "symbolic"))
      (lci-fail "relation-undetermined" "AdmissibilityUndetermined" "subject-time"
                :path '("left")))
    (when (or (string= lf "atemporal") (string= rf "atemporal"))
      (return-from temporal-relation (%relation-id "disjoint")))
    (when (and (string= lf "periodic-set") (string= rf "periodic-set"))
      (let ((lm (%temporal-int left "modulus"))
            (lr (%temporal-int left "remainder"))
            (rm (%temporal-int right "modulus"))
            (rr (%temporal-int right "remainder")))
        (return-from temporal-relation
          (%relation-id (if (and (= lm rm) (= lr rr)) "equal" "disjoint")))))
    (let ((li (%interval-view left)) (ri (%interval-view right)))
      (unless (and li ri)
        (lci-fail "relation-undetermined" "AdmissibilityUndetermined" "subject-time"
                  :path '("left")))
      (destructuring-bind (ls le lsc lec &rest lx) li
        (declare (ignore lx))
        (destructuring-bind (rs re rsc rec &rest rx) ri
          (declare (ignore rx))
          (cond ((%endpoint-before-p le lec rs rsc) (%relation-id "before"))
                ((%endpoint-before-p re rec ls lsc) (%relation-id "after"))
                ((%interval-contains-p li ri) (%relation-id "contains"))
                ((%interval-contains-p ri li) (%relation-id "contained-by"))
                (t (%relation-id "overlap"))))))))

(defun dataset-slice-relation (left right)
  (validate-dataset-slice left)
  (validate-dataset-slice right)
  (if (equal-datum left right) (%relation-id "equal")
      (let ((lf (exact-form-name (record-field-named left "expression")))
            (rf (exact-form-name (record-field-named right "expression"))))
        (cond ((string= lf "all-members") (%relation-id "wider"))
              ((string= rf "all-members") (%relation-id "narrower"))
              (t (%relation-id "incomparable"))))))

(defun semantic-boundary-relation (left right)
  (validate-semantic-boundary left)
  (validate-semantic-boundary right)
  (if (equal-datum left right) (%relation-id "equal")
      (%relation-id "incomparable")))
