;;;; p-q2-census.lisp — read-only census of the lane's external surface.
(require :sb-introspect)
(load "mneme/memory-layer-0/ml0-suite-ground.lisp")
(let* ((pkg (find-package '#:lisp-plus-memory-layer0))
       (loader (find-package '#:lisp-plus-memory-layer0-loader))
       (declared (symbol-value (find-symbol "+ML0-EXTERNAL-FUNCTIONS+" loader)))
       (dvars (symbol-value (find-symbol "+ML0-EXTERNAL-VARIABLES+" loader)))
       (dtypes (symbol-value (find-symbol "+ML0-EXTERNAL-TYPES+" loader)))
       (ext '()) (fb '()) (macros '()) (odd '()))
  (do-external-symbols (s pkg) (push s ext))
  (setf ext (remove-duplicates ext))
  (dolist (s ext) (when (fboundp s) (push s fb)))
  (dolist (s fb) (when (macro-function s) (push s macros)))
  (format t "~&(a) external symbols: ~d~%" (length ext))
  (format t "(b) fboundp externals (what F1 walks): ~d~%" (length fb))
  (format t "    declared +ml0-external-functions+: ~d~%" (length declared))
  (format t "    declared vars ~d  types ~d  sum ~d~%"
          (length dvars) (length dtypes)
          (+ (length declared) (length dvars) (length dtypes)))
  (let ((missing (sort (loop for s in fb
                             unless (member (symbol-name s) declared :test #'string=)
                               collect (symbol-name s))
                       #'string<)))
    (format t "(c) fboundp externals NOT in the loader list: ~d~%" (length missing))
    (dolist (n missing) (format t "      ~a~%" n)))
  (let ((notf (sort (loop for n in declared
                          unless (let ((s (find-symbol n pkg))) (and s (fboundp s)))
                            collect n)
                    #'string<)))
    (format t "(d) declared names NOT fboundp: ~d~%" (length notf))
    (dolist (n notf) (format t "      ~a~%" n)))
  (format t "(e) fboundp externals that are MACROS: ~d~%" (length macros))
  (dolist (s (sort (mapcar #'symbol-name macros) #'string<)) (format t "      ~a~%" s))
  ;; does function-lambda-list work on macros / signal / return odd?
  (format t "~%--- function-lambda-list behaviour over every fboundp external ---~%")
  (dolist (s (sort (copy-list fb) #'string< :key #'symbol-name))
    (multiple-value-bind (ll err)
        (handler-case (values (sb-introspect:function-lambda-list s) nil)
          (error (e) (values :--signalled-- (princ-to-string e))))
      (cond (err (push (list (symbol-name s) :signalled err) odd))
            ((eq ll :--signalled--) (push (list (symbol-name s) :signalled "?") odd))
            ((null ll) (push (list (symbol-name s) :empty-arglist
                                   (if (macro-function s) "macro" "function")) odd)))))
  (format t "odd/empty/signalling: ~d~%" (length odd))
  (dolist (o (reverse odd)) (format t "      ~s~%" o))
  ;; explicit macro check
  (format t "~%--- macro arglists explicitly ---~%")
  (dolist (s macros)
    (format t "      ~a => ~s~%" (symbol-name s)
            (handler-case (sb-introspect:function-lambda-list s)
              (error (e) (list :error (princ-to-string e))))))
  ;; how many fboundp externals have a DEFECT-ish param today
  (let ((off (loop for s in fb
                   when (some (lambda (i) (and (symbolp i)
                                               (member (symbol-name i) '("DEFECT" "DEFECT-PAYLOAD")
                                                       :test #'string=)))
                              (handler-case (sb-introspect:function-lambda-list s) (error () nil)))
                     collect (symbol-name s))))
    (format t "~%(f) current DEFECT offenders: ~d ~s~%" (length off) off)))
(finish-output)
