(defpackage #:lisp-plus-kernel0
  (:use #:cl)

  ;; CONDITIONS -- typed condition taxonomy and lawful restart names.
  (:export
   #:kernel0-condition
   #:kernel0-condition-process-id
   #:kernel0-condition-attempt-id
   #:kernel0-condition-seat-id
   #:kernel0-condition-operation-id
   #:kernel0-condition-failed-invariant
   #:kernel0-condition-evidence-ids
   #:kernel0-condition-frontier-crossed-p
   #:kernel0-condition-permitted-restarts
   #:kernel0-condition-requirement-id
   #:kernel0-condition-offending-field
   #:kernel0-condition-offending-value
   #:malformed-constructor-shape
   #:determinacy-mode-invalid
   #:determinacy-alternatives-invalid
   #:global-uncertainty-scalar-rejected
   #:interpretation-class-violation
   #:unresolved-identity
   #:duplicate-process-identity
   #:duplicate-seat-identity
   #:duplicate-attempt-identity
   #:duplicate-external-request-identity
   #:seat-occupied
   #:attempt-terminal
   #:identity-drift
   #:capability-missing
   #:capability-revoked
   #:capability-expired
   #:capability-scope-mismatch
   #:capability-budget-exceeded
   #:capability-count-exceeded
   #:capability-restoration-denied
   #:capability-self-restoration-forbidden
   #:capability-restoration-scope-enlarged
   #:minting-authority-invalid
   #:frontier-precondition-failed
   #:frontier-already-crossed
   #:unresolved-irreversible-effect
   #:unsafe-retry
   #:unstructured-uncertainty
   #:implicit-fallback-forbidden
   #:supersession-required
   #:supersession-unauthorized
   #:reconciliation-unsupported
   #:reconciliation-insufficient
   #:manifestation-payload-missing
   #:present-payload-erasure
   #:invalidity-parser-missing
   #:partial-manifestation-settlement-inflation
   #:interpretation-procedure-missing
   #:store-unavailable
   #:store-append-failed
   #:store-durability-unknown
   #:journal-prefix-invalid
   #:journal-torn-tail
   #:journal-illegal-transition
   #:journal-merge-receipt-required
   #:fold-nondeterministic
   #:standing-inflation
   #:witness-separation-violation
   #:reconstruction-origin-erasure
   #:bare-visibility-scope
   #:bare-validation-scope
   #:exposed-principal-missing
   #:noncanonical-durable-value
   #:machine-configuration-drift
   #:adapter-version-drift
   #:channel-policy-missing
   #:channel-policy-amendment-unauthorized
   #:publication-authority-missing
   #:outcome-context-discard
   #:unsafe-host-escape
   #:unsupported-reconstruction
   #:signal-kernel0
   #:with-kernel0-restarts
   #:supply-resolved-identity
   #:choose-private-staging-channel
   #:request-lawful-capability-restoration
   #:begin-reconciliation
   #:authorize-supersession
   #:preserve-payload-mark-invalid
   #:stop-and-export-evidence)

  ;; IDENTITY -- domain-tagged durable identities.
  (:export
   #:+identity-procedure+
   #:durable-identity
   #:durable-identity-p
   #:durable-identity-domain
   #:durable-identity-name
   #:make-identity
   #:identity=
   #:identity-key
   #:require-identity
   #:identity->datum
   #:datum->identity)

  ;; BOUNDARY -- identified host-to-CD/0 canonicalization procedures.
  (:export
   #:+identity-canonicalization-procedure-id+
   #:+string-canonicalization-procedure-id+
   #:+integer-canonicalization-procedure-id+
   #:+keyword-canonicalization-procedure-id+
   #:+proper-list-canonicalization-procedure-id+
   #:register-canonicalization-procedure
   #:require-canonical)

  ;; DETERMINACY -- later worker export section; append symbols here.
  (:export
   #:determinacy
   #:determinacy-p
   #:make-determinacy
   #:determinacy-mode
   #:determinacy-alternatives
   #:determinacy-evidence)

  ;; MANIFESTATION -- later worker export section; append symbols here.
  (:export
   #:manifestation-status-p
   #:absence-state-p
   #:present-manifestation-status-p
   #:manifestation
   #:manifestation-p
   #:make-manifestation
   #:manifestation-manifestation-id
   #:manifestation-attempt-id
   #:manifestation-kind
   #:manifestation-status
   #:manifestation-payload-id
   #:manifestation-absence-state
   #:manifestation-parser-id
   #:manifestation-source-boundary
   #:manifestation-visibility
   #:manifestation-emptiness-rule-id
   ;; Errata 0.2 §5 (K0E-27..32): producer identity + stream lineage
   ;; (consolidated from W2b-FLUMEN).
   #:manifestation-adapter-identity
   #:manifestation-producer-identity
   #:manifestation-stream-relation
   #:manifestation-chunk-record-ids
   #:manifestation-projection-receipt-id
   #:stream-relation
   #:stream-relation-p
   #:stream-relation-stream-id
   #:stream-relation-relation-kind
   #:stream-relation-chunk-record-ids
   #:stream-relation-projection-receipt-id
   #:validate-stream-relation-coherence
   #:causal-claim
   #:causal-claim-p
   #:make-causal-claim
   #:revise-causal-claim
   #:causal-claim-subject
   #:causal-claim-predicate
   #:causal-claim-evidence
   #:causal-claim-origin
   #:causal-claim-validation)

  ;; OUTCOME -- later worker export section; append symbols here.
  (:export
   #:axis
   #:axis-p
   #:axis-value
   #:axis-determinacy
   #:axis-evidence
   #:axis-procedure-id
   #:axis-frontier-qualifier
   #:axis-uncertain-effect-ref
   #:axis-effect-group
   #:axis-judgment-class
   #:axis-procedure-version
   #:make-execution-axis
   #:make-manifestation-axis
   #:make-effect-axis
   #:make-interpretation-axis
   #:outcome
   #:outcome-p
   #:make-outcome
   #:outcome-outcome-version
   #:outcome-process-id
   #:outcome-logical-operation-id
   #:outcome-seat-id
   #:outcome-attempt-id
   #:outcome-machine-configuration-id
   #:outcome-interpretation-descriptor
   #:outcome-receipts
   #:outcome-bounded-unknowns
   #:outcome-axis)

  ;; PROCEDURE -- K0E-23/K0E-25 procedure descriptors + judgment-class law,
  ;; K0E-26 joint verdicts (structural vs. semantic).
  (:export
   #:procedure-descriptor
   #:procedure-descriptor-p
   #:make-procedure-descriptor
   #:procedure-descriptor-procedure-id
   #:procedure-descriptor-version
   #:procedure-descriptor-judgment-class
   #:procedure-descriptor-input-domain
   #:procedure-descriptor-result-vocabulary
   #:procedure-descriptor-evidence-requirements
   #:procedure-descriptor-bounded-unknowns
   #:validate-interpretation-against-descriptor
   #:verdict
   #:verdict-p
   #:make-verdict
   #:verdict-value
   #:verdict-procedure-id
   #:verdict-condition-ids
   #:verdict-requirement-ids
   #:joint-verdict
   #:joint-verdict-p
   #:make-joint-verdict
   #:joint-verdict-structural
   #:joint-verdict-semantic
   #:joint-verdict-divergent-p)

  ;; UNCERTAIN-EFFECT -- later worker export section; append symbols here.
  (:export
   #:uncertain-effect
   #:uncertain-effect-p
   #:make-uncertain-effect
   #:uncertain-effect-kind
   #:uncertain-effect-attempt
   #:uncertain-effect-external-request
   #:uncertain-effect-possible-effects
   #:uncertain-effect-known-facts
   #:uncertain-effect-reconciliation-procedure
   #:uncertain-effect-retry-policy)

  ;; RECORDS -- later worker export section; append symbols here.
  (:export
   #:seat
   #:seat-p
   #:make-seat
   #:seat-seat-id
   #:seat-logical-operation-id
   #:seat-occupancy-domain-id
   #:seat-constraints
   #:attempt
   #:attempt-p
   #:make-attempt
   #:attempt-attempt-id
   #:attempt-logical-operation-id
   #:attempt-seat-id
   #:attempt-process-id
   #:attempt-predecessor-attempts
   #:attempt-exposure-id
   #:attempt-machine-configuration-id
   #:attempt-external-request-id
   #:attempt-supersession-records
   #:supersession
   #:supersession-p
   #:make-supersession
   #:supersession-receipt-id
   #:supersession-seat-id
   #:supersession-predecessor-attempt-id
   #:supersession-superseding-attempt-id
   #:supersession-authorized-by
   #:supersession-reason
   #:supersession-fresh-exposure-p
   #:supersession-precedence-rule
   #:supersession-cost-effect-treatment
   #:supersession-residual-unknowns
   #:reconciliation-receipt
   #:reconciliation-receipt-p
   #:make-reconciliation-receipt
   #:reconciliation-receipt-target-attempt-id
   #:reconciliation-receipt-procedure-id
   #:reconciliation-receipt-procedure-version
   #:reconciliation-receipt-new-evidence
   #:reconciliation-receipt-previous-axis-values+determinacy
   #:reconciliation-receipt-resulting-axis-values+determinacy
   #:reconciliation-receipt-unresolved-residue
   #:role-assignment
   #:role-assignment-p
   #:make-role-assignment
   #:role-assignment-scope
   #:role-assignment-principal-id
   #:role-assignment-role
   #:role-assignment-source
   #:role-assignment-effective-interval
   #:exposure-record
   #:exposure-record-p
   #:make-exposure-record
   #:exposure-record-protected-object-id
   #:exposure-record-exposing-action
   #:exposure-record-receiving-principals
   #:exposure-record-scope
   #:exposure-record-mode
   #:exposure-record-evidence
   #:exposure-record-induced-restrictions
   #:capability-mint-receipt
   #:capability-mint-receipt-p
   #:make-capability-mint-receipt
   #:capability-mint-receipt-receipt-id
   #:capability-mint-receipt-capability-id
   #:capability-mint-receipt-minted-by
   #:capability-mint-receipt-authorizing-claim-id
   #:capability-mint-receipt-derived-scope
   #:capability-mint-receipt-delegates
   #:capability-mint-receipt-revocation-registry
   #:capability-mint-receipt-expiry
   #:capability-restoration-receipt
   #:capability-restoration-receipt-p
   #:make-capability-restoration-receipt
   #:capability-restoration-receipt-receipt-id
   #:capability-restoration-receipt-predecessor-capability-id
   #:capability-restoration-receipt-new-capability-id
   #:capability-restoration-receipt-restored-by
   #:capability-restoration-receipt-authority-basis
   #:capability-restoration-receipt-revocation-check
   #:capability-restoration-receipt-unresolved-effect-check
   #:capability-restoration-receipt-old-scope
   #:capability-restoration-receipt-new-scope
   #:claim
   #:claim-p
   #:make-claim
   #:claim-claim-id
   #:claim-content-datum
   #:claim-source-ids
   #:claim-origin
   #:claim-validation-records
   #:claim-integrity-records
   #:claim-visibility-records
   #:claim-determinacy
   #:claim-bounded-unknowns
   #:revalidate-claim
   #:promote-origin
   ;; Errata 0.2 §3 (K0E-18..22): claim-standing records + scoped queries
   ;; (consolidated from W2a-LIMES).
   #:validation-record
   #:validation-record-p
   #:make-validation-record
   #:validation-record-status
   #:validation-record-subject-id
   #:validation-record-validator-principal-id
   #:validation-record-procedure-id
   #:validation-record-procedure-version
   #:validation-record-scope
   #:validation-record-evidence
   #:validation-record-bounded-unknowns
   #:integrity-record
   #:integrity-record-p
   #:make-integrity-record
   #:integrity-record-status
   #:integrity-record-subject-id
   #:integrity-record-representation-id
   #:integrity-record-method-id
   #:integrity-record-method-version
   #:integrity-record-sealing-principal-id
   #:integrity-record-evidence
   #:integrity-record-bounded-unknowns
   #:visibility-record
   #:visibility-record-p
   #:make-visibility-record
   #:visibility-record-status
   #:visibility-record-subject-id
   #:visibility-record-representation-id
   #:visibility-record-scope-id
   #:visibility-record-authorizing-basis
   #:visibility-record-redaction-receipt-id
   #:visibility-record-evidence
   #:visibility-record-bounded-unknowns
   #:derive-claim
   #:claim-validated-under-p
   #:claim-published-to-p)

  ;; FOLDS -- later worker export section; append symbols here.
  (:export
   #:+kernel0-event-types+
   #:kernel0-event-type-p
   #:kernel0-event
   #:kernel0-event-p
   #:make-kernel0-event
   #:kernel0-event-event-type
   #:kernel0-event-extension-p
   #:kernel0-event-process-id
   #:kernel0-event-logical-operation-id
   #:kernel0-event-seat-id
   #:kernel0-event-attempt-id
   #:kernel0-event-external-request-id
   #:kernel0-event-exposure-id
   #:kernel0-event-machine-configuration-id
   #:kernel0-event-effect-id
   #:kernel0-event-manifestation-id
   #:kernel0-event-payload
   #:validate-event-sequence
   #:check-retry-safety
   #:fold-seat-occupancy
   #:fold-exposure-principals
   #:attempt-outcome-standing
   #:attempt-outcome-standing-p
   #:attempt-outcome-standing-attempt-id
   #:attempt-outcome-standing-terminal-class
   #:attempt-outcome-standing-unresolved-effect-p
   #:attempt-outcome-standing-unresolved-effects
   #:attempt-outcome-standing-supersession-lineage
   #:attempt-outcome-standing-original-axis-values+determinacy
   #:attempt-outcome-standing-current-axis-values+determinacy
   #:attempt-outcome-standing-reconciliation-receipts
   #:fold-attempt-outcome
   #:merge-event-sequences))
