(in-package #:leibnitiana)

;;;; -------------------------------------------------------------------------
;;;; Judgments: binary substrate without epistemic bivalence
;;;; -------------------------------------------------------------------------

(defparameter +epistemic-statuses+
  '(:supported :refuted :undetermined :conflicted :out-of-jurisdiction)
  "Statuses understood by the constitutional branch operator JIF.")

(defstruct (judgment
            (:constructor make-judgment
                (&key value
                      (status :undetermined)
                      premises boundary authority procedure notes)))
  "A value accompanied by the conditions under which it may testify.

The structure deliberately keeps VALUE and STATUS separate. A non-NIL value is
not thereby supported, and an unknown status is never silently promoted to
truth merely because Common Lisp conditionals treat it as truthy."
  value
  status
  premises
  boundary
  authority
  procedure
  notes)

(define-condition epistemic-status-error (error)
  ((status :initarg :status :reader epistemic-status-error-status)
   (judgment :initarg :judgment :reader epistemic-status-error-judgment))
  (:report
   (lambda (condition stream)
     (format stream
             "Judgment status ~S has no licensed branch. The calculation has a result, but not standing."
             (epistemic-status-error-status condition)))))

(defun judgment-standing-p (judgment)
  "True only when JUDGMENT has an explicitly supported or refuted standing."
  (member (judgment-status judgment) '(:supported :refuted) :test #'eq))

(defmacro jif (judgment-form &body clauses)
  "Branch on a JUDGMENT's epistemic status without truthiness coercion.

Syntax:
  (jif judgment
    (:supported ...)
    (:refuted ...)
    (:otherwise ...))

The :OTHERWISE clause is optional. Without it, an unhandled status signals
EPISTEMIC-STATUS-ERROR. Each status may appear at most once."
  (let ((g (gensym "JUDGMENT-"))
        (status (gensym "STATUS-"))
        (seen '())
        (case-clauses '())
        (otherwise-body nil))
    (dolist (clause clauses)
      (unless (and (consp clause) (keywordp (first clause)))
        (error "Malformed JIF clause: ~S" clause))
      (let ((key (first clause))
            (body (rest clause)))
        (when (member key seen :test #'eq)
          (error "Duplicate JIF clause for ~S" key))
        (push key seen)
        (if (eq key :otherwise)
            (setf otherwise-body body)
            (push `(,key ,@body) case-clauses))))
    `(let* ((,g ,judgment-form)
            (,status (judgment-status ,g)))
       (case ,status
         ,@(nreverse case-clauses)
         (otherwise
          ,(if otherwise-body
               `(progn ,@otherwise-body)
               `(error 'epistemic-status-error
                       :status ,status
                       :judgment ,g)))))))

;;;; -------------------------------------------------------------------------
;;;; Windowless evaluators: closure as bounded monad interface
;;;; -------------------------------------------------------------------------

(defun make-monad (id initial-state law &key (deposition #'identity))
  "Create a closure whose transition LAW receives only private state and TICK.

LAW must accept (STATE TICK) and return two values: NEW-STATE and PERCEPTION.
DEPOSITION maps the latest perception into the public testimony emitted by
DEPOSE-MONAD. The supported interface exposes no operation for reading or
writing the private state directly.

This is interface-level windowlessness, not a metaphysical guarantee. A LAW can
still cheat by consulting ambient global state; storms/hidden-operator.lisp is
an executable counterexample."
  (let ((state initial-state)
        (latest-perception nil)
        (last-tick nil))
    (lambda (message &optional argument)
      (ecase message
        (:id id)
        (:advance
         (multiple-value-bind (new-state perception)
             (funcall law state argument)
           (setf state new-state
                 latest-perception perception
                 last-tick argument)
           perception))
        (:deposition
         (list :monad id
               :tick last-tick
               :testimony (funcall deposition latest-perception)
               :boundary :public-perception-only))))))

(defun monad-id (monad)
  (funcall monad :id))

(defun advance-monad (monad tick)
  (funcall monad :advance tick))

(defun depose-monad (monad)
  (funcall monad :deposition))

(defun run-harmony (monads ticks &key (stream *standard-output*))
  "Advance every monad through TICKS and print their public depositions.

No monad is passed another monad or a universe object. Apparent coordination is
therefore generated by each law's own unfolding over the common tick. The
shared tick and this scheduler remain privileged infrastructure and should not
be confused with a proof of metaphysical independence."
  (dolist (tick ticks)
    (format stream "~&TICK ~D~%" tick)
    (dolist (monad monads)
      (advance-monad monad tick)
      (format stream "  ~S~%" (depose-monad monad))))
  monads)



;;;; -------------------------------------------------------------------------
;;;; Compossibility: consistency indexed by a declared world
;;;; -------------------------------------------------------------------------

(defstruct (claim
            (:constructor make-claim
                (&key id proposition constraints boundary)))
  "A proposition plus the dimensions required for it to inhabit a world.

CONSTRAINTS is an association list such as:
  ((:corpus-version . :v2) (:time . 2026) (:jurisdiction . :local))

Two claims are compossible when every dimension they both constrain agrees.
The marker :ANY is compatible with every value but does not establish that a
more specific alignment has actually been checked."
  id
  proposition
  constraints
  boundary)

(defun %constraint-value (dimension constraints)
  (cdr (assoc dimension constraints :test #'eq)))

(defun %constraint-dimensions (constraints)
  (mapcar #'car constraints))

(defun %compatible-constraint-values-p (left right)
  (or (eq left :any)
      (eq right :any)
      (equal left right)))

(defun compossibility-report (left right)
  "Return an inspectable report for whether LEFT and RIGHT can share a world.

This is deliberately weaker than truth adjudication. It detects incompatible
shared constraints; it does not prove either proposition, nor does it prove
that unshared dimensions are irrelevant."
  (let* ((left-dims (%constraint-dimensions (claim-constraints left)))
         (right-dims (%constraint-dimensions (claim-constraints right)))
         (shared (intersection left-dims right-dims :test #'eq))
         (conflicts
           (loop for dimension in shared
                 for left-value = (%constraint-value dimension
                                                      (claim-constraints left))
                 for right-value = (%constraint-value dimension
                                                       (claim-constraints right))
                 unless (%compatible-constraint-values-p left-value right-value)
                   collect (list :dimension dimension
                                 :left left-value
                                 :right right-value))))
    (list :compossible (null conflicts)
          :left (claim-id left)
          :right (claim-id right)
          :shared-dimensions shared
          :conflicts conflicts
          :unshared-left (set-difference left-dims right-dims :test #'eq)
          :unshared-right (set-difference right-dims left-dims :test #'eq)
          :boundary :constraint-alignment-only)))

(defun compossible-p (left right)
  (getf (compossibility-report left right) :compossible))

;;;; -------------------------------------------------------------------------
;;;; Inspectable contracts: macroexpansion as close reading
;;;; -------------------------------------------------------------------------

(defvar *evaluator-contracts* (make-hash-table :test #'eq))

(defun evaluator-contract (name)
  "Return the declared operational contract for NAME, or NIL."
  (gethash name *evaluator-contracts*))

(defmacro defwindowless-evaluator (name lambda-list &body body)
  "Define an evaluator and register the bounded meaning of 'windowless'.

Macroexpansion intentionally reveals the caveats that the surface adjective
would otherwise conceal. The generated function receives only its declared
arguments, but ambient state, implementation introspection, and privileged
runtime observation remain outside the claim."
  `(progn
     (setf (gethash ',name *evaluator-contracts*)
           '(:surface-claim :windowless
             :interface-claim :no-peer-reference-supplied
             :enforcement-claim :not-established
             :ambient-state :not-audited
             :implementation-introspection :out-of-scope
             :runtime-visibility :privileged
             :standing :interface-relative-only))
     (defun ,name ,lambda-list
       ,@body)))

;;;; -------------------------------------------------------------------------
;;;; Tiny dependency-free smoke-test helpers
;;;; -------------------------------------------------------------------------

(defun print-section (title &optional (stream *standard-output*))
  (format stream "~&~%=== ~A ===~%" title))

(defun check (condition description)
  (unless condition
    (error "CHECK failed: ~A" description))
  (format t "[pass] ~A~%" description)
  t)

(defun check-equal (expected actual description &key (test #'equal))
  (check (funcall test expected actual)
         (format nil "~A — expected ~S, got ~S"
                 description expected actual)))
