;;;; JSONL machine adapter for the independent Common Lisp CD/0 seed.
;;;;
;;;; The adapter owns protocol translation only.  Datum construction, equality,
;;;; encoding, decoding, budgets, and fixture conversion all go through the
;;;; seed's exported API.  The seed test harness supplies its dependency-free,
;;;; data-only JSON parser; loading it does not execute the test suite.

(load "canonical-datum/common-lisp/package.lisp")
(load "canonical-datum/common-lisp/cd0.lisp")
(load "canonical-datum/common-lisp/tests.lisp")

(defpackage #:lisp-plus-cd0-integration-adapter
  (:use #:cl #:lisp-plus-cd0))

(in-package #:lisp-plus-cd0-integration-adapter)

(defparameter +protocol+ "lisp-plus-cd0-differential/v1")
(defparameter +implementation+ "common-lisp")

(defun jget (object key &optional (default nil default-supplied-p))
  (if default-supplied-p
      (lisp-plus-cd0-tests::jget object key default)
      (lisp-plus-cd0-tests::jget object key)))

(defun json-string (value stream)
  (write-char #\" stream)
  (loop for character across value
        for code = (char-code character)
        do (case character
             (#\" (write-string "\\\"" stream))
             (#\\ (write-string "\\\\" stream))
             (#\Backspace (write-string "\\b" stream))
             (#\Page (write-string "\\f" stream))
             (#\Newline (write-string "\\n" stream))
             (#\Return (write-string "\\r" stream))
             (#\Tab (write-string "\\t" stream))
             (otherwise
              (if (< code #x20)
                  (format stream "\\u~4,'0x" code)
                  (write-char character stream)))))
  (write-char #\" stream))

(defun json-key (value stream)
  (json-string value stream)
  (write-char #\: stream))

(defun write-json-string-array (items stream)
  (write-char #\[ stream)
  (loop for item in items
        for first = t then nil
        unless first do (write-char #\, stream)
        do (json-string item stream))
  (write-char #\] stream))

(defun write-fixture-ast (ast stream)
  (let ((tag (jget ast "t")))
    (write-char #\{ stream)
    (json-key "t" stream)
    (json-string tag stream)
    (cond
      ((string= tag "unit"))
      ((string= tag "bool")
       (write-char #\, stream)
       (json-key "v" stream)
       (write-string (if (jget ast "v") "true" "false") stream))
      ((string= tag "int")
       (write-char #\, stream)
       (json-key "v" stream)
       (json-string (jget ast "v") stream))
      ((string= tag "rat")
       (write-char #\, stream)
       (json-key "p" stream)
       (json-string (jget ast "p") stream)
       (write-char #\, stream)
       (json-key "q" stream)
       (json-string (jget ast "q") stream))
      ((string= tag "string")
       (write-char #\, stream)
       (json-key "utf8_hex" stream)
       (json-string (jget ast "utf8_hex") stream))
      ((string= tag "bytes")
       (write-char #\, stream)
       (json-key "hex" stream)
       (json-string (jget ast "hex") stream))
      ((string= tag "id")
       (write-char #\, stream)
       (json-key "namespace_utf8_hex" stream)
       (write-json-string-array (jget ast "namespace_utf8_hex") stream)
       (write-char #\, stream)
       (json-key "path_utf8_hex" stream)
       (write-json-string-array (jget ast "path_utf8_hex") stream))
      ((string= tag "seq")
       (write-char #\, stream)
       (json-key "items" stream)
       (write-char #\[ stream)
       (loop for item in (jget ast "items")
             for first = t then nil
             unless first do (write-char #\, stream)
             do (write-fixture-ast item stream))
       (write-char #\] stream))
      ((string= tag "record")
       (write-char #\, stream)
       (json-key "fields" stream)
       (write-char #\[ stream)
       (loop for field in (jget ast "fields")
             for first = t then nil
             unless first do (write-char #\, stream)
             do (write-char #\{ stream)
                (json-key "key" stream)
                (write-fixture-ast (jget field "key") stream)
                (write-char #\, stream)
                (json-key "value" stream)
                (write-fixture-ast (jget field "value") stream)
                (write-char #\} stream))
       (write-char #\] stream))
      (t (error "unsupported fixture AST tag ~S" tag)))
    (write-char #\} stream)))

(defun request-budget (request)
  (apply #'make-resource-budget
         :id (jget request "budget_id")
         (lisp-plus-cd0-tests::budget-overrides (jget request "budget"))))

(defun write-response-prefix (request-id status stream)
  (write-char #\{ stream)
  (json-key "protocol" stream)
  (json-string +protocol+ stream)
  (write-char #\, stream)
  (json-key "implementation" stream)
  (json-string +implementation+ stream)
  (write-char #\, stream)
  (json-key "request_id" stream)
  (json-string request-id stream)
  (write-char #\, stream)
  (json-key "status" stream)
  (json-string status stream))

(defun emit-failure (request-id condition)
  (write-response-prefix request-id "failure" *standard-output*)
  (write-char #\, *standard-output*)
  (json-key "failure" *standard-output*)
  (write-char #\{ *standard-output*)
  (json-key "category" *standard-output*)
  (json-string (failure-category condition) *standard-output*)
  (write-char #\, *standard-output*)
  (json-key "code" *standard-output*)
  (json-string (failure-code condition) *standard-output*)
  (write-char #\, *standard-output*)
  (json-key "stage" *standard-output*)
  (json-string (failure-stage condition) *standard-output*)
  (write-string "}}" *standard-output*)
  (terpri))

(defun emit-not-applicable (request-id reason)
  (write-response-prefix request-id "not-applicable" *standard-output*)
  (write-char #\, *standard-output*)
  (json-key "reason" *standard-output*)
  (json-string reason *standard-output*)
  (write-char #\} *standard-output*)
  (terpri))

(defun emit-datum-result (request-id datum budget)
  (write-response-prefix request-id "ok" *standard-output*)
  (write-char #\, *standard-output*)
  (json-key "result" *standard-output*)
  (write-char #\{ *standard-output*)
  (json-key "canonical_hex" *standard-output*)
  (json-string (octets-to-hex (encode-exact datum :budget budget))
               *standard-output*)
  (write-char #\, *standard-output*)
  (json-key "fixture_ast" *standard-output*)
  (write-fixture-ast (datum-to-fixture-ast datum) *standard-output*)
  (write-string "}}" *standard-output*)
  (terpri))

(defun emit-roundtrip (request-id datum budget)
  (let* ((encoded (encode-exact datum :budget budget))
         (decoded (decode-exact encoded :budget budget)))
    (write-response-prefix request-id "ok" *standard-output*)
    (write-char #\, *standard-output*)
    (json-key "result" *standard-output*)
    (write-char #\{ *standard-output*)
    (json-key "canonical_hex" *standard-output*)
    (json-string (octets-to-hex encoded) *standard-output*)
    (write-char #\, *standard-output*)
    (json-key "fixture_ast" *standard-output*)
    (write-fixture-ast (datum-to-fixture-ast decoded) *standard-output*)
    (write-char #\, *standard-output*)
    (json-key "reencoded_hex" *standard-output*)
    (json-string (octets-to-hex (encode-exact decoded :budget budget))
                 *standard-output*)
    (write-char #\, *standard-output*)
    (json-key "constructed_equal_decoded" *standard-output*)
    (write-string (if (equal-datum datum decoded) "true" "false")
                  *standard-output*)
    (write-string "}}" *standard-output*)
    (terpri)))

(defun emit-equality (request-id left right budget)
  (write-response-prefix request-id "ok" *standard-output*)
  (write-char #\, *standard-output*)
  (json-key "result" *standard-output*)
  (write-char #\{ *standard-output*)
  (json-key "equal" *standard-output*)
  (write-string (if (equal-datum left right) "true" "false")
                *standard-output*)
  (write-char #\, *standard-output*)
  (json-key "left_hex" *standard-output*)
  (json-string (octets-to-hex (encode-exact left :budget budget))
               *standard-output*)
  (write-char #\, *standard-output*)
  (json-key "right_hex" *standard-output*)
  (json-string (octets-to-hex (encode-exact right :budget budget))
               *standard-output*)
  (write-string "}}" *standard-output*)
  (terpri))

(defun host-import (request budget)
  (let ((importer (jget request "importer")))
    ;; The Common Lisp seed declares only the generic sequence fixture rows
    ;; applicable.  Its seed suite constructs the corresponding hostile host
    ;; shapes directly, which this adapter repeats without interpreting other
    ;; implementations' descriptors.
    (cond
      ((not (string= importer "generic-sequence-import/v0"))
       (emit-not-applicable
        (jget request "request_id")
        "Common Lisp seed does not expose this optional host importer"))
      ((string= (jget request "case_id") "cd0-neg-host-cycle")
       (let* ((ast (list (cons "t" "seq") (cons "items" nil)))
              (items (list ast)))
         (setf (cdr (assoc "items" ast :test #'string=)) items)
         (emit-datum-result
          (jget request "request_id")
          (datum-from-fixture-ast ast :budget budget) budget)))
      ((string= (jget request "case_id") "cd0-neg-host-improper-list")
       (let ((improper (cons (make-integer-datum 1)
                             (make-integer-datum 2))))
         (emit-datum-result
          (jget request "request_id")
          (make-sequence-datum improper :budget budget) budget)))
      (t
       (error "unknown generic sequence fixture case")))))

(defun process-request-body (request request-id operation budget)
  (cond
          ((string= operation "construct-roundtrip")
           (emit-roundtrip
            request-id
            (datum-from-fixture-ast (jget request "ast") :budget budget)
            budget))
          ((string= operation "decode")
           (emit-datum-result
            request-id
            (decode-exact (hex-to-octets (jget request "input_hex"))
                          :budget budget)
            budget))
          ((string= operation "decode-probe")
           (let* ((datum
                    (decode-exact (hex-to-octets (jget request "input_hex"))
                                  :budget budget))
                  (encoded (encode-exact datum :budget budget)))
             (write-response-prefix request-id "ok" *standard-output*)
             (write-char #\, *standard-output*)
             (json-key "result" *standard-output*)
             (write-char #\{ *standard-output*)
             (json-key "reencoded_hex" *standard-output*)
             (json-string (octets-to-hex encoded) *standard-output*)
             (write-string "}}" *standard-output*)
             (terpri)))
          ((string= operation "host-import")
           (host-import request budget))
          ((string= operation "equal")
           (emit-equality
            request-id
            (datum-from-fixture-ast (jget request "left_ast") :budget budget)
            (datum-from-fixture-ast (jget request "right_ast") :budget budget)
            budget))
          ((string= operation "fixture-import")
           (emit-datum-result
            request-id
            (datum-from-fixture-ast (jget request "ast") :budget budget)
            budget))
          ((string= operation "nested-encode")
           (let ((datum (make-unit-datum)))
             (loop repeat (1- (jget request "depth"))
                   do (setf datum (make-sequence-datum (list datum))))
             (let ((encoded (encode-exact datum :budget budget)))
               (write-response-prefix request-id "ok" *standard-output*)
               (write-char #\, *standard-output*)
               (json-key "result" *standard-output*)
               (write-char #\{ *standard-output*)
               (json-key "canonical_hex" *standard-output*)
               (json-string (octets-to-hex encoded) *standard-output*)
               (write-char #\, *standard-output*)
               (json-key "datum_depth" *standard-output*)
               (write (jget request "depth") :stream *standard-output*
                      :base 10 :radix nil)
               (write-string "}}" *standard-output*)
               (terpri))))
          (t (error "unsupported operation ~S" operation))))

(defun process-request (request)
  (unless (string= (jget request "protocol") +protocol+)
    (error "unsupported protocol"))
  (let* ((request-id (jget request "request_id"))
         (operation (jget request "op"))
         (budget (request-budget request))
         (destination *standard-output*))
    ;; Construct each response in a private string stream.  If a later codec
    ;; step fails after an earlier field was rendered, the unfinished response
    ;; is discarded and exactly one typed-failure line is published.
    (handler-case
        (let ((response
                (with-output-to-string (stream)
                  (let ((*standard-output* stream))
                    (process-request-body request request-id operation budget)))))
          (write-string response destination))
      (cd0-failure (condition)
        (let ((*standard-output* destination))
          (emit-failure request-id condition))))))

(defun request-path ()
  (or (car (last sb-ext:*posix-argv*))
      (error "missing request path")))

(handler-case
    (progn
      (loop for request in (lisp-plus-cd0-tests::read-jsonl (request-path))
            do (process-request request))
      (finish-output)
      (sb-ext:exit :code 0))
  (condition (condition)
    (format *error-output* "Common Lisp adapter fatal: ~A~%" condition)
    (sb-debug:print-backtrace :stream *error-output* :count 30)
    (sb-ext:exit :code 2)))
